const express = require('express');
const router = express.Router();
const nodemailer = require('nodemailer');
const Product = require('../models/Product');
const Supplier = require('../models/Supplier');
const PurchaseOrder = require('../models/PurchaseOrder');
const Transaction = require('../models/Transaction');
const { checkAndCreateAlert } = require('../services/alertService');

/* ─────────────────────────────────────────────
   POST /api/purchase-orders/send
   Body: { supplierId, items: [{ productId, productName, quantity, price }], note }
───────────────────────────────────────────── */
router.post('/send', async (req, res) => {
  try {
    const { supplierId, items, note } = req.body;

    if (!supplierId || !items || items.length === 0) {
      return res.status(400).json({ message: 'Supplier and at least one item are required.' });
    }

    const supplier = await Supplier.findById(supplierId);
    if (!supplier) return res.status(404).json({ message: 'Supplier not found.' });
    if (!supplier.email) return res.status(400).json({ message: `Supplier "${supplier.name}" has no email address on file.` });

    // Calculate totals
    const totalAmount = items.reduce((sum, item) => sum + item.quantity * item.price, 0);
    const orderDate = new Date().toLocaleString('en-IN', { dateStyle: 'full', timeStyle: 'short' });

    // Build HTML email body
    const itemRows = items.map((item, i) => `
      <tr style="background:${i % 2 === 0 ? '#f8f9fc' : '#fff'}">
        <td style="padding:10px 14px;border-bottom:1px solid #eee;">${i + 1}. ${item.productName}</td>
        <td style="padding:10px 14px;border-bottom:1px solid #eee;text-align:center;">${item.quantity}</td>
        <td style="padding:10px 14px;border-bottom:1px solid #eee;text-align:right;">₹${Number(item.price).toLocaleString('en-IN')}</td>
        <td style="padding:10px 14px;border-bottom:1px solid #eee;text-align:right;font-weight:600;">₹${(item.quantity * item.price).toLocaleString('en-IN')}</td>
      </tr>`).join('');

    const htmlBody = `
<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"></head>
<body style="margin:0;padding:0;font-family:'Segoe UI',Arial,sans-serif;background:#f0f2f5;">
  <div style="max-width:680px;margin:30px auto;background:#fff;border-radius:12px;overflow:hidden;box-shadow:0 4px 24px rgba(0,0,0,0.08);">
    
    <!-- Header -->
    <div style="background:linear-gradient(135deg,#5438dc,#7c3aed);padding:32px 36px;">
      <h1 style="color:#fff;margin:0;font-size:22px;font-weight:700;">📦 Purchase Order Request</h1>
      <p style="color:#c4b5fd;margin:6px 0 0;font-size:13px;">Smart Inventory Crud Web Application With NLP</p>
    </div>

    <!-- Order Info -->
    <div style="padding:28px 36px;background:#fafbff;border-bottom:1px solid #eee;">
      <p style="margin:0 0 6px;color:#555;font-size:13px;">Date: <strong>${orderDate}</strong></p>
      <p style="margin:0;color:#555;font-size:13px;">To: <strong>${supplier.name}</strong></p>
      ${note ? `<p style="margin:10px 0 0;color:#555;font-size:13px;">Note: <em>${note}</em></p>` : ''}
    </div>

    <!-- Items Table -->
    <div style="padding:28px 36px;">
      <h2 style="font-size:15px;color:#333;margin:0 0 16px;font-weight:600;">Order Items</h2>
      <table style="width:100%;border-collapse:collapse;font-size:14px;">
        <thead>
          <tr style="background:#5438dc;">
            <th style="padding:10px 14px;color:#fff;text-align:left;font-weight:600;">Product</th>
            <th style="padding:10px 14px;color:#fff;text-align:center;font-weight:600;">Qty</th>
            <th style="padding:10px 14px;color:#fff;text-align:right;font-weight:600;">Unit Price</th>
            <th style="padding:10px 14px;color:#fff;text-align:right;font-weight:600;">Total</th>
          </tr>
        </thead>
        <tbody>
          ${itemRows}
        </tbody>
        <tfoot>
          <tr style="background:#f0eeff;">
            <td colspan="3" style="padding:14px;font-weight:700;font-size:15px;color:#5438dc;text-align:right;">Grand Total</td>
            <td style="padding:14px;font-weight:700;font-size:15px;color:#5438dc;text-align:right;">₹${totalAmount.toLocaleString('en-IN')}</td>
          </tr>
        </tfoot>
      </table>
    </div>

    <!-- Footer -->
    <div style="padding:20px 36px;background:#f8f9fc;text-align:center;border-top:1px solid #eee;">
      <p style="margin:0;color:#999;font-size:12px;">This is an automated purchase order generated by Smart Inventory Crud Web Application With NLP.</p>
      <p style="margin:4px 0 0;color:#999;font-size:12px;">Please confirm receipt and expected delivery timeline.</p>
    </div>
  </div>
</body>
</html>`;

    // Configure transporter
    const transporter = nodemailer.createTransport({
      service: 'gmail',
      auth: {
        user: process.env.EMAIL_USER,
        pass: process.env.EMAIL_PASS
      }
    });

    await transporter.sendMail({
      from: `"Smart Inventory" <${process.env.EMAIL_USER}>`,
      to: supplier.email,
      subject: `📦 Purchase Order from Smart Inventory — ${orderDate}`,
      html: htmlBody
    });

    // Save to database
    await PurchaseOrder.create({
      supplier: supplierId,
      items: items.map(item => ({
        product: item.productId || null,
        productName: item.productName,
        quantity: item.quantity,
        price: item.price
      })),
      totalAmount,
      note,
      status: 'sent'
    });

    res.json({
      success: true,
      message: `Order email sent successfully to ${supplier.name} (${supplier.email})`,
      totalAmount,
      itemCount: items.length
    });

  } catch (err) {
    console.error('Purchase order email error:', err);
    res.status(500).json({ message: err.message || 'Failed to send order email.' });
  }
});

/* ─────────────────────────────────────────────
   GET /api/purchase-orders
   Fetch all purchase orders
   ───────────────────────────────────────────── */
router.get('/', async (req, res) => {
  try {
    const orders = await PurchaseOrder.find()
      .populate('supplier')
      .sort('-createdAt');
    res.json(orders);
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
});

/* ─────────────────────────────────────────────
   PUT /api/purchase-orders/:id/status
   Update purchase order status. If changing to 'received',
   auto-refill inventory stock levels and log transaction.
   ───────────────────────────────────────────── */
router.put('/:id/status', async (req, res) => {
  try {
    const { status } = req.body;
    if (!['sent', 'confirmed', 'received'].includes(status)) {
      return res.status(400).json({ message: 'Invalid status value.' });
    }

    const order = await PurchaseOrder.findById(req.id || req.params.id);
    if (!order) return res.status(404).json({ message: 'Purchase order not found.' });

    // Prevent double adding stock
    if (order.status === 'received') {
      return res.status(400).json({ message: 'This purchase order has already been marked as received. Stock was already updated.' });
    }

    // If transitioning to received, update inventory quantities
    if (status === 'received') {
      for (const item of order.items) {
        let productObj = null;

        // Try lookup by productId ref first, then fallback to name
        if (item.product) {
          productObj = await Product.findById(item.product);
        }
        if (!productObj) {
          productObj = await Product.findOne({ name: item.productName });
        }

        if (productObj) {
          const previousQuantity = productObj.quantity;
          productObj.quantity += item.quantity;
          await productObj.save();

          // Link product ID back to the order item for cleaner data integrity
          item.product = productObj._id;

          // Log transaction
          await Transaction.create({
            product: productObj._id,
            type: 'add',
            quantity: item.quantity,
            previousQuantity,
            newQuantity: productObj.quantity,
            reason: `B2B Restock: Received Purchase Order (ID: ${order._id})`
          });

          // Run alert check
          await checkAndCreateAlert(productObj);
        }
      }
    }

    order.status = status;
    await order.save();

    res.json({
      success: true,
      message: `Purchase order status successfully updated to "${status}".`,
      order
    });

  } catch (err) {
    console.error('Update purchase order status error:', err);
    res.status(500).json({ message: err.message });
  }
});

module.exports = router;
