import React, { createContext, useState, useContext, useEffect } from 'react';

const translations = {
  en: {
    sidebar: {
      dashboard: "Dashboard",
      products: "Products",
      stock: "Stock",
      ledger: "Stock Ledger",
      suppliers: "Suppliers",
      voice: "Voice",
      chat: "Chat",
      aiReport: "AI Report",
      reports: "Reports",
      createInvoice: "Create Invoice",
      allInvoices: "All Invoices",
      purchaseOrder: "Purchase Order",
      profile: "Profile",
      settings: "Settings"
    },
    dashboard: {
      title: "Inventory Overview",
      subtitle: "AI-powered analytics and realtime tracking",
      live: "System Live",
      voiceAi: "Voice AI",
      createInvoice: "Create Invoice",
      stockLedger: "Stock Ledger",
      manageProducts: "Manage Products",
      totalProducts: "Total Products",
      inventoryValue: "Inventory Value",
      lowOutStock: "Low & Out of Stock",
      topStocked: "Top Stocked Products",
      healthScore: "Health Score",
      healthCalculated: "Calculated based on current stock levels",
      criticalAlerts: "Critical Alerts",
      healthyMsg: "Inventory is perfectly healthy!",
      lowStockAlerts: "Low Stock Alerts",
      needsRestock: "Needs Restock",
      minStock: "Min Stock Level",
      qty: "Qty",
      restockBtn: "Reorder",
      highDemand: "High Demand Products",
      topSellers: "Top Sellers (30d)",
      sold: "Sold",
      recentTransactions: "Recent Transactions",
      viewLedger: "View Ledger",
      noActivity: "No recent activity detected.",
      loading: "Loading dashboard...",
      inStock: "In Stock",
      lowStock: "Low Stock",
      outOfStock: "Out of Stock"
    },
    products: {
      title: "Product Catalog",
      subtitle: "View and manage your smart inventory items",
      searchPlaceholder: "Search products by name, category, or SKU...",
      addProductBtn: "Add Product",
      id: "ID",
      name: "Product Name",
      sku: "SKU",
      category: "Category",
      quantity: "Quantity",
      price: "Price",
      minStock: "Min Stock",
      actions: "Actions",
      edit: "Edit",
      delete: "Delete",
      noProducts: "No products found.",
      addNewTitle: "Add New Product",
      editTitle: "Edit Product",
      saveBtn: "Save",
      cancelBtn: "Cancel",
      categoryPlaceholder: "Select Category",
      priceLabel: "Price (₹)",
      qtyLabel: "Initial Quantity",
      minStockLabel: "Min Stock Level",
      loading: "Loading products...",
      optional: "Optional",
      saveErrorMsg: "Error saving product",
      createBtn: "Create Product"
    },
    stock: {
      title: "Stock Management",
      subtitle: "Quickly restock or deplete inventory items",
      selectProduct: "Select Product",
      chooseProduct: "Choose a product...",
      action: "Action",
      add: "Add Stock (Restock)",
      remove: "Remove Stock (Deplete)",
      quantity: "Quantity",
      notes: "Notes / Description",
      notesPlaceholder: "e.g., Supplier shipment, damaged goods...",
      submitBtn: "Update Stock",
      successMsg: "Stock updated successfully",
      errorMsg: "Failed to update stock",
      loading: "Loading stock..."
    },
    ledger: {
      title: "Stock Movement History",
      subtitle: "Real-time audit log of all inventory changes",
      date: "Date & Time",
      product: "Product",
      type: "Type",
      change: "Change",
      user: "User",
      notes: "Notes",
      added: "Added",
      removed: "Deleted",
      loading: "Loading history..."
    },
    suppliers: {
      title: "Supplier Management",
      subtitle: "Manage inventory suppliers and partners",
      addSupplier: "Add Supplier",
      name: "Supplier Name",
      contact: "Contact Person",
      email: "Email Address",
      phone: "Phone Number",
      address: "Address",
      actions: "Actions",
      noSuppliers: "No suppliers registered.",
      addNewTitle: "Add New Supplier",
      editTitle: "Edit Supplier",
      saveBtn: "Save",
      cancelBtn: "Cancel",
      loading: "Loading suppliers..."
    },
    voice: {
      title: "Voice AI Controller",
      subtitle: "Control your inventory using natural speech commands",
      listening: "Listening...",
      clickMic: "Click the mic to speak your command",
      exampleTitle: "Try saying commands like:",
      ex1: 'Show me all products with low stock',
      ex2: 'Add 50 laptops to stock',
      ex3: 'Update price of Table to 1500',
      status: "AI Engine Status",
      connected: "Ready",
      lastCommand: "Last processed command:",
      processing: "Processing...",
      commandResult: "Result:",
      speechUnsupported: "Web Speech API is not supported in this browser. Please use Chrome.",
      noCommands: "No commands recorded yet.",
      ex4: "Show inventory",
      ex5: "What is total inventory value?"
    },
    chat: {
      title: "Chat with Inventory AI",
      subtitle: "Ask questions or execute commands using natural language",
      placeholder: "Type your command (e.g. Add 20 Chairs)...",
      send: "Send",
      welcome: "Hello! I am your Smart Inventory Assistant. You can manage stock, update prices, or run queries here. Try: 'Show low stock products'",
      loading: "AI is thinking..."
    },
    aiReport: {
      title: "AI Report Generator",
      subtitle: "Generate dynamic PDF reports with AI-powered health analysis",
      generateBtn: "Generate PDF Report",
      previewBtn: "Preview Report",
      analyzing: "Analyzing data with AI...",
      generationSuccess: "PDF generated successfully!"
    },
        reports: {
      title: "Inventory Reports",
      subtitle: "Visual reports and inventory health audit",
      downloadExcel: "Download Excel",
      downloadPdf: "Download PDF",
      valueDistribution: "Stock Value Distribution",
      categoryAnalysis: "Category Analysis",
      generalHealth: "General Health",
      orderPlacement: "Order Placement",
      restocking: "Restocking",
      refresh: "Refresh",
      deadStock: "Dead Stock",
      stockMovementTrend: "Stock Movement Trend",
      inventoryHealth: "Inventory Health",
      aiHealthScore: "AI Inventory Health Score",
      goodStanding: "Good Standing",
      needsAttention: "Needs Attention",
      critical: "Critical",
      inventoryValueByProduct: "Inventory Value by Product",
      fastMovingProducts: "Fast Moving Products",
      deadStockItems: "Dead Stock Items",
      activeStockAlerts: "Active Stock Alerts",
      transactionHistory: "Transaction History",
      dateTime: "Date & Time",
      type: "Type",
      previous: "Previous",
      newStock: "New Stock",
      totalB2BSpend: "Total B2B Spend",
      totalOrdersPlaced: "Total Purchase Orders Placed",
      avgOrderValue: "Average Order Value",
      spendBySupplier: "Spend by Supplier",
      topProductsProcured: "Top 5 Products by Procured Value",
      purchaseOrdersLog: "B2B Purchase Orders Log",
      products: "Items",
      status: "Status",
      received: "Received",
      sent: "Sent",
      confirmed: "Confirmed",
      totalSpend: "Total Ordered Value (₹)",
      totalReplenished: "Units Replenished",
      estimatedRestockingCost: "Estimated Restocking Cost",
      restockingCount: "Restocking Count",
      replenishmentTrend: "Replenishment Volume Trend",
      restockTriggers: "Restock Refill Triggers",
      replenishmentLog: "Replenishment History Log",
      qty: "Quantity Added",
      user: "User",
      errorMsg: "Failed to generate report. Please ensure the backend is running and Groq API key is configured.",
      print: "Print",
      generating: "Generating...",
      regenerateBtn: "Regenerate Report",
      generateBtn: "Generate AI Report",
      noReport: "No Report Generated Yet",
      emptyDesc: "Click 'Generate AI Report' above to create a comprehensive, AI-powered analysis of your inventory — including health scores, dead stock identification, risk alerts, and strategic recommendations.",
      execSummary: "Executive Summary",
      movementAnalysis: "Movement Analysis",
      aiRecommendations: "AI Recommendations",
      reportTitle: "Inventory Analysis Report",
      generatedOn: "Generated on"
    },
    invoice: {
      title: "Create Invoice",
      subtitle: "Generate billing invoice for customers",
      billTo: "Bill To",
      clientName: "Client Name",
      clientEmail: "Client Email",
      invoiceDate: "Invoice Date",
      addItem: "Add Item",
      product: "Product",
      qty: "Quantity",
      price: "Price (?)",
      total: "Total",
      generateBtn: "Generate Invoice",
      invoicesList: "All Invoices",
      selectSupplier: "Select Supplier...",
      grandTotal: "Grand Total",
      typeLabel: "Billing Type",
      sales: "Sales",
      purchase: "Purchase",
      walkInCustomer: "Walk-in Customer",
      itemsTitle: "Bill Items",
      selectProduct: "Select Product...",
      preview: "Invoice Preview",
      allSuppliers: "All Suppliers",
      noInvoices: "No invoices found.",
      subtotal: "Subtotal",
      supplier: "Supplier"
    },
    invoices: {
      title: "Invoice Ledger",
      subtitle: "View and manage generated customer invoices",
      invoiceNum: "Invoice #",
      client: "Client Name",
      date: "Date",
      amount: "Amount",
      actions: "Actions",
      viewPdf: "View PDF"
    },
    purchaseOrder: {
      title: "B2B Purchase Orders",
      subtitle: "Order stock from verified suppliers",
      createBtn: "Create Purchase Order",
      supplier: "Supplier",
      products: "Products",
      orderDate: "Order Date",
      status: "Status",
      totalPrice: "Total Price",
      statusSent: "Sent",
      statusConfirmed: "Confirmed",
      statusReceived: "Received",
      cart: "Order Cart",
      emptyCart: "No items selected yet",
      clickAdd: "Click a product on the left to add",
      sending: "Sending Order Email...",
      added: "Added — Click to Add More",
      addBtn: "Add to Order",
      noSupplierEmail: "This supplier has no email address. Please update their profile first.",
      notePlaceholder: "e.g. Please deliver by Friday, handle with care...",
      noteFooter: "A formatted purchase order email will be sent directly to the selected supplier."
    },
    profile: {
      title: "My Profile",
      subtitle: "Manage your account and view project credits",
      logout: "Logout",
      aboutTitle: "About the Project",
      developedBy: "Developed By",
      aboutP1: "The Smart Inventory Crud Web Application With NLP is a web-based system that helps manage inventory in a simple and efficient way. It allows users to add, view, update, and delete product data easily.",
      aboutP2: "What makes this system \"smart\" is the use of Natural Language Processing (NLP). Users can give commands in simple language instead of going through complex steps, making the system faster and easier to use.",
      aboutP3: "This project shows how modern technology can improve traditional inventory systems by making them more user-friendly and intelligent."
    },
    settings: {
      title: "Settings",
      subtitle: "Configure your system preferences",
      languageLabel: "System Language",
      selectLanguage: "Select Language",
      saveSettings: "Save Settings",
      successMsg: "Language updated successfully!"
    }
  },
  mr: {
    sidebar: {
      dashboard: "डॅशबोर्ड",
      products: "उत्पादने",
      stock: "स्टॉक",
      ledger: "स्टॉक लेजर",
      suppliers: "पुरवठादार",
      voice: "आवाज",
      chat: "चॅट",
      aiReport: "एआय रिपोर्ट",
      reports: "अहवाल",
      createInvoice: "इन्व्हॉइस तयार करा",
      allInvoices: "सर्व इन्व्हॉइसेस",
      purchaseOrder: "खरेदी आदेश",
      profile: "प्रोफाइल",
      settings: "सेटिंग्ज"
    },
    dashboard: {
      title: "इन्व्हेंटरी विहंगावलोकन",
      subtitle: "एआय-संचलित विश्लेषण आणि रिअलटाइम ट्रॅकिंग",
      live: "सिस्टम लाइव्ह",
      voiceAi: "व्हॉइस एआय",
      createInvoice: "इन्व्हॉइस तयार करा",
      stockLedger: "स्टॉक लेजर",
      manageProducts: "उत्पादने व्यवस्थापित करा",
      totalProducts: "एकूण उत्पादने",
      inventoryValue: "इन्व्हेंटरी मूल्य",
      lowOutStock: "कमी आणि संपलेला स्टॉक",
      topStocked: "सर्वाधिक साठा असलेली उत्पादने",
      healthScore: "आरोग्य गुण (Health Score)",
      healthCalculated: "सध्याच्या स्टॉक पातळीच्या आधारे गणना केली",
      criticalAlerts: "गंभीर इशारे",
      healthyMsg: "इन्व्हेंटरी पूर्णपणे निरोगी आहे!",
      lowStockAlerts: "कमी स्टॉक इशारे",
      needsRestock: "पुन्हा भरणे आवश्यक आहे",
      minStock: "किमान स्टॉक पातळी",
      qty: "प्रमाण",
      restockBtn: "पुन्हा खरेदी करा",
      highDemand: "जास्त मागणी असलेली उत्पादने",
      topSellers: "टॉप विक्रेते (३० दिवस)",
      sold: "विकले",
      recentTransactions: "अलीकडील व्यवहार",
      viewLedger: "लेजर पहा",
      noActivity: "कोणतीही अलीकडील क्रिया आढळली नाही.",
      loading: "डॅशबोर्ड लोड होत आहे...",
      inStock: "स्टॉकमध्ये आहे",
      lowStock: "कमी स्टॉक",
      outOfStock: "स्टॉक संपला"
    },
    products: {
      title: "उत्पादन कॅटलॉग",
      subtitle: "तुमच्या स्मार्ट इन्व्हेंटरी वस्तू पहा आणि व्यवस्थापित करा",
      searchPlaceholder: "नाव, श्रेणी किंवा SKU द्वारे उत्पादने शोधा...",
      addProductBtn: "उत्पादन जोडा",
      id: "आयडी",
      name: "उत्पादनाचे नाव",
      sku: "SKU",
      category: "श्रेणी",
      quantity: "प्रमाण",
      price: "किंमत",
      minStock: "किमान स्टॉक",
      actions: "कृती",
      edit: "संपादन",
      delete: "हटवा",
      noProducts: "उत्पादने आढळली नाहीत.",
      addNewTitle: "नवीन उत्पादन जोडा",
      editTitle: "उत्पादन संपादन",
      saveBtn: "जतन करा",
      cancelBtn: "रद्द करा",
      categoryPlaceholder: "श्रेणी निवडा",
      priceLabel: "किंमत (₹)",
      qtyLabel: "प्रारंभिक प्रमाण"
    },
    stock: {
      title: "स्टॉक व्यवस्थापन",
      subtitle: "इन्व्हेंटरी वस्तू त्वरीत पुन्हा भरा किंवा कमी करा",
      selectProduct: "उत्पादन निवडा",
      chooseProduct: "उत्पादन निवडा...",
      action: "कृती",
      add: "स्टॉक जोडा (Restock)",
      remove: "स्टॉक कमी करा (Deplete)",
      quantity: "प्रमाण",
      notes: "नोंदी / वर्णन",
      notesPlaceholder: "उदा. पुरवठादार शिपमेंट, खराब झालेला माल...",
      submitBtn: "स्टॉक अपडेट करा",
      successMsg: "स्टॉक यशस्वीरित्या अपडेट झाला",
      errorMsg: "स्टॉक अपडेट करण्यात अयशस्वी",
      loading: "स्टॉक लोड होत आहे..."
    },
    ledger: {
      title: "स्टॉक हालचाल इतिहास",
      subtitle: "सर्व इन्व्हेंटरी बदलांचा रिअल-टाइम ऑडिट लॉग",
      date: "तारीख आणि वेळ",
      product: "उत्पादन",
      type: "प्रकार",
      change: "बदल",
      user: "वापरकर्ता",
      notes: "नोंदी",
      added: "जोडले",
      removed: "हटवले",
      loading: "इतिहास लोड होत आहे..."
    },
    voice: {
      title: "व्हॉइस एआय नियंत्रक",
      subtitle: "नैसर्गिक भाषेद्वारे तुमच्या इन्व्हेंटरीवर नियंत्रण ठेवा",
      listening: "ऐकत आहे...",
      clickMic: "तुमची आज्ञा बोलण्यासाठी माइकवर क्लिक करा",
      exampleTitle: "यासारख्या आज्ञा बोलून पहा:",
      ex1: "कमी स्टॉक असलेली सर्व उत्पादने दाखवा",
      ex2: "स्टॉकमध्ये ५० लॅपटॉप जोडा",
      ex3: "टेबलची किंमत १५०० पर्यंत अपडेट करा",
      status: "एआय इंजिन स्थिती",
      connected: "तयार",
      lastCommand: "शेवटची प्रक्रिया केलेली आज्ञा:",
      processing: "प्रक्रिया करत आहे...",
      commandResult: "निकाल:",
      speechUnsupported: "या ब्राउझरमध्ये वेब स्पीच API समर्थित नाही. कृपया क्रोम वापरा.",
      noCommands: "अद्याप कोणत्याही आज्ञा नोंदवलेल्या नाहीत.",
      ex4: "इन्व्हेंटरी दाखवा",
      ex5: "एकूण इन्व्हेंटरी मूल्य काय आहे?"
    },
    chat: {
      title: "इन्व्हेंटरी एआय सोबत चॅट करा",
      subtitle: "नैसर्गिक भाषेचा वापर करून प्रश्न विचारा किंवा आज्ञा कार्यान्वित करा",
      placeholder: "तुमची आज्ञा टाईप करा (उदा. २० खुर्च्या जोडा)...",
      send: "पाठवा",
      welcome: "नमस्कार! मी तुमचा स्मार्ट इन्व्हेंटरी सहाय्यक आहे. तुम्ही येथे स्टॉक व्यवस्थापित करू शकता, किंमती अपडेट करू शकता किंवा प्रश्न विचारू शकता. प्रयत्न करा: 'कमी स्टॉक उत्पादने दाखवा'",
      loading: "एआय विचार करत आहे..."
    },
    aiReport: {
      title: "एआय अहवाल जनरेटर",
      subtitle: "एआय-संचलित आरोग्य विश्लेषणासह डायनॅमिक PDF अहवाल तयार करा",
      generateBtn: "PDF अहवाल तयार करा",
      previewBtn: "अहवाल पूर्वावलोकन",
      analyzing: "एआय सह डेटा विश्लेषण करत आहे...",
      generationSuccess: "PDF यशस्वीरित्या तयार झाली!"
    },
        reports: {
      title: "अहवाल",
      subtitle: "दृश्य अहवाल आणि इन्व्हेंटरी आरोग्य ऑडिट",
      downloadExcel: "एक्सेल डाउनलोड करा",
      downloadPdf: "PDF डाउनलोड करा",
      valueDistribution: "स्टॉक मूल्य वितरण",
      categoryAnalysis: "श्रेणी विश्लेषण",
      generalHealth: "सामान्य आरोग्य",
      orderPlacement: "ऑर्डर प्लेसमेंट",
      restocking: "पुन्हा साठा भरणे",
      refresh: "ताजे करा",
      deadStock: "डेड स्टॉक",
      stockMovementTrend: "स्टॉक हालचाल ट्रेंड",
      inventoryHealth: "इन्व्हेंटरी आरोग्य",
      aiHealthScore: "AI इन्व्हेंटरी आरोग्य धावसंख्या",
      goodStanding: "चांगली स्थिती",
      needsAttention: "लक्ष देणे आवश्यक आहे",
      critical: "गंभीर",
      inventoryValueByProduct: "उत्पादनानुसार इन्व्हेंटरी मूल्य",
      fastMovingProducts: "जलद हालणारी उत्पादने",
      deadStockItems: "डेड स्टॉक वस्तू",
      activeStockAlerts: "सक्रिय स्टॉक अलर्ट",
      transactionHistory: "व्यवहार इतिहास",
      dateTime: "तारीख आणि वेळ",
      type: "प्रकार",
      previous: "मागील साठा",
      newStock: "नवीन साठा",
      totalB2BSpend: "एकूण B2B खर्च",
      totalOrdersPlaced: "एकूण खरेदी ऑर्डर",
      avgOrderValue: "सरासरी ऑर्डर मूल्य",
      spendBySupplier: "पुरवठादारानुसार खर्च",
      topProductsProcured: "procure केलेले सर्वोच्च ५ उत्पादने",
      purchaseOrdersLog: "B2B खरेदी ऑर्डर लॉग",
      products: "वस्तू",
      status: "स्थिती",
      received: "मिळाले",
      sent: "पाठवले",
      confirmed: "पुष्टी केली",
      totalSpend: "एकूण ऑर्डर मूल्य (₹)",
      totalReplenished: "पुन्हा भरलेले युनिट्स",
      estimatedRestockingCost: "अंदाजित रिस्टॉकिंग खर्च",
      restockingCount: "रिस्टॉकिंग गणना",
      replenishmentTrend: "रिस्टॉकिंग व्हॉल्यूम ट्रेंड",
      restockTriggers: "रिस्टॉकिंग ट्रिगर्स",
      replenishmentLog: "रिस्टॉकिंग इतिहास लॉग",
      qty: "प्रमाण जोडले",
      user: "वापरकर्ता",
      errorMsg: "अहवाल तयार करण्यात अयशस्वी. कृपया बॅकएंड चालू असल्याची खात्री करा.",
      print: "मुद्रित करा",
      generating: "तयार होत आहे...",
      regenerateBtn: "अहवाल पुन्हा तयार करा",
      generateBtn: "AI अहवाल तयार करा",
      noReport: "अजून कोणताही अहवाल तयार केलेला नाही",
      emptyDesc: "तुमच्या इन्व्हेंटरीचे तपशीलवार AI अहवाल तयार करण्यासाठी वर 'AI अहवाल तयार करा' वर क्लिक करा.",
      execSummary: "कार्यकारी सारांश",
      movementAnalysis: "हालचाल विश्लेषण",
      aiRecommendations: "AI शिफारसी",
      reportTitle: "इन्व्हेंटरी विश्लेषण अहवाल",
      generatedOn: "रोजी तयार केले"
    },
    invoice: {
      title: "इन्व्हॉइस तयार करा",
      subtitle: "ग्राहकांसाठी बिलिंग इन्व्हॉइस तयार करा",
      billTo: "बिल पत्ता",
      clientName: "ग्राहकाचे नाव",
      clientEmail: "ग्राहकाचा ईमेल",
      invoiceDate: "इन्व्हॉइस तारीख",
      addItem: "आयटम जोडा",
      product: "उत्पादन",
      qty: "प्रमाण",
      price: "किंमत (₹)",
      total: "एकूण",
      generateBtn: "इन्व्हॉइस तयार करा",
      invoicesList: "सर्व इन्व्हॉइसेस",
      selectSupplier: "पुरवठादार निवडा...",
      grandTotal: "एकूण एकूण",
      typeLabel: "बिलिंग प्रकार",
      sales: "विक्री",
      purchase: "खरेदी",
      walkInCustomer: "थेट ग्राहक",
      itemsTitle: "बिल आयटम",
      selectProduct: "उत्पादन निवडा...",
      preview: "इन्व्हॉइसचे पूर्वदृश्य",
      allSuppliers: "सर्व पुरवठादार",
      noInvoices: "कोणतेही इन्व्हॉइस सापडले नाही.",
      subtotal: "उप-एकूण",
      supplier: "पुरवठादार"
    },
    invoices: {
      title: "इन्व्हॉइस लेजर",
      subtitle: "तयार केलेले ग्राहक इन्व्हॉइसेस पहा आणि व्यवस्थापित करा",
      invoiceNum: "इन्व्हॉइस #",
      client: "ग्राहकाचे नाव",
      date: "तारीख",
      amount: "रक्कम",
      actions: "कृती",
      viewPdf: "PDF पहा"
    },
    purchaseOrder: {
      title: "B2B खरेदी आदेश",
      subtitle: "नोंदणीकृत पुरवठादारांकडून माल मागवा",
      createBtn: "खरेदी आदेश तयार करा",
      supplier: "पुरवठादार",
      products: "उत्पादने",
      orderDate: "आदेश तारीख",
      status: "स्थिती",
      totalPrice: "एकूण किंमत",
      statusSent: "पाठवले",
      statusConfirmed: "निश्चित",
      statusReceived: "मिळाले",
      cart: "ऑर्डर कार्ट",
      emptyCart: "अद्याप कोणतीही वस्तू निवडलेली नाही",
      clickAdd: "जोडण्यासाठी डावीकडील उत्पादनावर क्लिक करा",
      sending: "ऑर्डर ईमेल पाठवत आहे...",
      added: "जोडले — अधिक जोडण्यासाठी क्लिक करा",
      addBtn: "ऑर्डरमध्ये जोडा",
      noSupplierEmail: "या पुरवठादाराचा ईमेल पत्ता नाही. कृपया आधी त्यांची प्रोफाइल अपडेट करा.",
      notePlaceholder: "उदा. कृपया शुक्रवारपर्यंत पोहोचवा, काळजीपूर्वक हाताळा...",
      noteFooter: "खरेदी आदेश थेट निवडलेल्या पुरवठादाराला ईमेल केला जाईल."
    },
    profile: {
      title: "माझी प्रोफाइल",
      subtitle: "तुमचे खाते व्यवस्थापित करा आणि प्रकल्प क्रेडिट्स पहा",
      logout: "बाहेर पडा",
      aboutTitle: "प्रकल्पाविषयी",
      developedBy: "विकसित केले",
      aboutP1: "एनएलपीसह स्मार्ट इन्व्हेंटरी क्रड वेब ॲप्लिकेशन ही एक वेब-आधारित प्रणाली आहे जी सोप्या आणि कार्यक्षम पद्धतीने साठा व्यवस्थापित करण्यास मदत करते. हे वापरकर्त्यांना उत्पादनाचा डेटा सहजपणे जोडण्यास, पाहण्यास, अपडेट करण्यास आणि हटविण्यास अनुमती देते.",
      aboutP2: "या प्रणालीला \"स्मार्ट\" बनवणारी गोष्ट म्हणजे नॅचरल लँग्वेज प्रोसेसिंग (NLP) चा वापर. वापरकर्ते क्लिष्ट पायऱ्यांमधून जाण्याऐवजी सोप्या भाषेत आज्ञा देऊ शकतात, ज्यामुळे ही प्रणाली जलद आणि वापरण्यास सोपी होते.",
      aboutP3: "हा प्रकल्प दाखवतो की आधुनिक तंत्रज्ञान पारंपारिक इन्व्हेंटरी प्रणालींना अधिक वापरकर्ता-अनुकूल आणि बुद्धिमान बनवून कशा प्रकारे सुधारू शकते."
    },
    settings: {
      title: "सेटिंग्ज",
      subtitle: "तुमची सिस्टम पसंती कॉन्गिफर करा",
      languageLabel: "सिस्टम भाषा",
      selectLanguage: "भाषा निवडा",
      saveSettings: "सेटिंग्ज जतन करा",
      successMsg: "भाषा यशस्वीरित्या अपडेट झाली!"
    }
  },
  hi: {
    sidebar: {
      dashboard: "डैशबोर्ड",
      products: "उत्पाद",
      stock: "स्टॉक",
      ledger: "स्टॉक लेजर",
      suppliers: "आपूर्तिकर्ता",
      voice: "आवाज़",
      chat: "चैट",
      aiReport: "एआई रिपोर्ट",
      reports: "रिपोर्ट",
      createInvoice: "इनवॉइस बनाएं",
      allInvoices: "सभी इनवॉइस",
      purchaseOrder: "खरीद आदेश",
      profile: "प्रोफ़ाइल",
      settings: "सेटिंग्स"
    },
    dashboard: {
      title: "इन्वेंटरी अवलोकन",
      subtitle: "एआई-संचालित विश्लेषण और रीयलटाइम ट्रैकिंग",
      live: "सिस्टम लाइव है",
      voiceAi: "वॉयस एआई",
      createInvoice: "इनवॉइस बनाएं",
      stockLedger: "स्टॉक लेजर",
      manageProducts: "उत्पादों का प्रबंधन",
      totalProducts: "कुल उत्पाद",
      inventoryValue: "इन्वेंटरी मूल्य",
      lowOutStock: "कम और समाप्त स्टॉक",
      topStocked: "शीर्ष स्टॉक वाले उत्पाद",
      healthScore: "हेल्थ स्कोर",
      healthCalculated: "वर्तमान स्टॉक स्तरों के आधार पर गणना",
      criticalAlerts: "महत्वपूर्ण अलर्ट",
      healthyMsg: "इन्वेंटरी पूरी तरह से स्वस्थ है!",
      lowStockAlerts: "कम स्टॉक अलर्ट",
      needsRestock: "पुनर्प्राप्ति की आवश्यकता है",
      minStock: "न्यूनतम स्टॉक स्तर",
      qty: "मात्रा",
      restockBtn: "पुनः ऑर्डर करें",
      highDemand: "उच्च मांग वाले उत्पाद",
      topSellers: "शीर्ष विक्रेता (30 दिन)",
      sold: "बेचे गए",
      recentTransactions: "हाल के लेन-देन",
      viewLedger: "लेजर देखें",
      noActivity: "कोई हाल की गतिविधि नहीं मिली।",
      loading: "डैशबोर्ड लोड हो रहा है..."
    },
    products: {
      title: "उत्पाद सूची",
      subtitle: "अपनी स्मार्ट इन्वेंटरी आइटम देखें और प्रबंधित करें",
      searchPlaceholder: "नाम, श्रेणी या SKU द्वारा उत्पाद खोजें...",
      addProductBtn: "उत्पाद जोड़ें",
      id: "आईडी",
      name: "उत्पाद का नाम",
      sku: "SKU",
      category: "श्रेणी",
      quantity: "मात्रा",
      price: "कीमत",
      minStock: "न्यूनतम स्टॉक",
      actions: "कार्रवाई",
      edit: "संपादित करें",
      delete: "हटाएं",
      noProducts: "कोई उत्पाद नहीं मिला।",
      addNewTitle: "नया उत्पाद जोड़ें",
      editTitle: "उत्पाद संपादित करें",
      saveBtn: "सहेजें",
      cancelBtn: "रद्द करें",
      categoryPlaceholder: "श्रेणी चुनें",
      priceLabel: "कीमत (₹)",
      qtyLabel: "प्रारंभिक मात्रा",
      minStockLabel: "न्यूनतम स्टॉक स्तर",
      loading: "उत्पाद लोड हो रहे हैं..."
    },
    stock: {
      title: "स्टॉक प्रबंधन",
      subtitle: "इन्वेंटरी आइटम को जल्दी से फिर से भरें या कम करें",
      selectProduct: "उत्पाद चुनें",
      chooseProduct: "उत्पाद चुनें...",
      action: "कार्रवाई",
      add: "स्टॉक जोड़ें (Restock)",
      remove: "स्टॉक हटाएं (Deplete)",
      quantity: "मात्रा",
      notes: "नोट्स / विवरण",
      notesPlaceholder: "उदा. आपूर्तिकर्ता शिपमेंट, क्षतिग्रस्त सामान...",
      submitBtn: "स्टॉक अपडेट करें",
      successMsg: "स्टॉक सफलतापूर्वक अपडेट किया गया",
      errorMsg: "स्टॉक अपडेट करने में विफल",
      loading: "स्टॉक लोड हो रहा है..."
    },
    ledger: {
      title: "स्टॉक मूवमेंट इतिहास",
      subtitle: "सभी इन्वेंट्री परिवर्तनों का रीयल-टाइम ऑडिट लॉग",
      date: "दिनांक और समय",
      product: "उत्पाद",
      type: "प्रकार",
      change: "बदलाव",
      user: "उपयोगकर्ता",
      notes: "नोट्स",
      added: "जोड़ा गया",
      removed: "हटाया गया (Deleted)",
      loading: "इतिहास लोड हो रहा है..."
    },
    suppliers: {
      title: "आपूर्तिकर्ता प्रबंधन",
      subtitle: "इन्वेंट्री आपूर्तिकर्ताओं और भागीदारों को प्रबंधित करें",
      addSupplier: "आपूर्तिकर्ता जोड़ें",
      name: "आपूर्तिकर्ता का नाम",
      contact: "संपर्क व्यक्ति",
      email: "ईमेल पता",
      phone: "फ़ोन नंबर",
      address: "पता",
      actions: "कार्रवाई",
      noSuppliers: "कोई आपूर्तिकर्ता पंजीकृत नहीं है।",
      addNewTitle: "नया आपूर्तिकर्ता जोड़ें",
      editTitle: "आपूर्तिकर्ता संपादित करें",
      saveBtn: "सहेजें",
      cancelBtn: "रद्द करें",
      loading: "आपूर्तिकर्ता लोड हो रहे हैं..."
    },
    voice: {
      title: "वॉयस एआई नियंत्रक",
      subtitle: "प्राकृतिक भाषण आदेशों का उपयोग करके अपनी इन्वेंट्री को नियंत्रित करें",
      listening: "सुन रहा हूँ...",
      clickMic: "अपनी आज्ञा बोलने के लिए माइक पर क्लिक करें",
      exampleTitle: "इस तरह की आज्ञा बोलने का प्रयास करें:",
      ex1: "कम स्टॉक वाले सभी उत्पाद दिखाएं",
      ex2: "स्टॉक में 50 लैपटॉप जोड़ें",
      ex3: "टेबल की कीमत 1500 तक अपडेट करें",
      status: "एआई इंजन स्थिति",
      connected: "तैयार",
      lastCommand: "अंतिम संसाधित आज्ञा:",
      processing: "प्रसंस्करण हो रहा है...",
      commandResult: "परिणाम:",
      speechUnsupported: "इस ब्राउज़र में वेब स्पीच API समर्थित नहीं है। कृपया क्रोम का उपयोग करें.",
      noCommands: "अभी तक कोई आदेश दर्ज नहीं किया गया है।",
      ex4: "इन्वेंटरी दिखाएं",
      ex5: "कुल इन्वेंटरी मूल्य क्या है?"
    },
    chat: {
      title: "इन्वेंटरी एआई के साथ चैट करें",
      subtitle: "प्राकृतिक भाषा का उपयोग करके प्रश्न पूछें या आदेश चलाएं",
      placeholder: "अपना आदेश टाइप करें (जैसे 20 कुर्सियाँ जोड़ें)...",
      send: "भेजें",
      welcome: "नमस्ते! मैं आपका स्मार्ट इन्वेंटरी सहायक हूँ। आप यहाँ स्टॉक प्रबंधित कर सकते हैं, कीमतें अपडेट कर सकते हैं या प्रश्न पूछ सकते हैं। प्रयास करें: 'कम स्टॉक वाले उत्पाद दिखाएं'",
      loading: "एआई सोच रहा है..."
    },
    aiReport: {
      title: "एआई रिपोर्ट जनरेटर",
      subtitle: "एआई-संचालित स्वास्थ्य विश्लेषण के साथ गतिशील पीडीएफ रिपोर्ट उत्पन्न करें",
      generateBtn: "पीडीएफ रिपोर्ट उत्पन्न करें",
      previewBtn: "रिपोर्ट पूर्वावलोकन",
      analyzing: "एआई के साथ डेटा का विश्लेषण किया जा रहा है...",
      generationSuccess: "पीडीएफ सफलतापूर्वक उत्पन्न हुआ!"
    },
        reports: {
      title: "इन्वेंटरी रिपोर्ट्स",
      subtitle: "दृश्य रिपोर्ट और इन्वेंटरी स्वास्थ्य ऑडिट",
      downloadExcel: "एक्सेल डाउनलोड करें",
      downloadPdf: "पीडीएफ डाउनलोड करें",
      valueDistribution: "स्टॉक मूल्य वितरण",
      categoryAnalysis: "श्रेणी विश्लेषण",
      generalHealth: "सामान्य स्वास्थ्य",
      orderPlacement: "ऑर्डर प्लेसमेंट",
      restocking: "पुनर्साधना",
      refresh: "ताज़ा करें",
      deadStock: "डेड स्टॉक",
      stockMovementTrend: "स्टॉक मूवमेंट ट्रेंड",
      inventoryHealth: "इन्वेंटरी स्वास्थ्य",
      aiHealthScore: "AI इन्वेंटरी स्वास्थ्य स्कोर",
      goodStanding: "अच्छी स्थिति",
      needsAttention: "ध्यान देने की आवश्यकता है",
      critical: "गंभीर",
      inventoryValueByProduct: "उत्पाद द्वारा इन्वेंटरी मूल्य",
      fastMovingProducts: "तेजी से बिकने वाले उत्पाद",
      deadStockItems: "डेड स्टॉक आइटम",
      activeStockAlerts: "सक्रिय स्टॉक अलर्ट",
      transactionHistory: "लेनदेन इतिहास",
      dateTime: "दिनांक और समय",
      type: "प्रकार",
      previous: "पिछला स्टॉक",
      newStock: "नया स्टॉक",
      totalB2BSpend: "कुल B2B खर्च",
      totalOrdersPlaced: "कुल खरीद आदेश",
      avgOrderValue: "औसत ऑर्डर मूल्य",
      spendBySupplier: "आपूर्तिकर्ता द्वारा खर्च",
      topProductsProcured: "शीर्ष 5 खरीद उत्पाद",
      purchaseOrdersLog: "B2B खरीद ऑर्डर लॉग",
      products: "आइटम",
      status: "स्थिति",
      received: "प्राप्त",
      sent: "भेजा गया",
      confirmed: "पुष्टि की गई",
      totalSpend: "कुल ऑर्डर मूल्य (₹)",
      totalReplenished: "पुनः भरे गए यूनिट्स",
      estimatedRestockingCost: "अनुमानित रिस्टॉकिंग लागत",
      restockingCount: "रिस्टॉकिंग गणना",
      replenishmentTrend: "रिस्टॉकिंग वॉल्यूम ट्रेंड",
      restockTriggers: "रिस्टॉकिंग ट्रिगर्स",
      replenishmentLog: "रिस्टॉकिंग इतिहास लॉग",
      qty: "मात्रा जोड़ी गई",
      user: "उपयोगकर्ता",
      errorMsg: "रिपोर्ट बनाने में विफल। कृपया सुनिश्चित करें कि बैकएंड चल रहा है और Groq API कुंजी कॉन्फ़िगर की गई है।",
      print: "प्रिंट करें",
      generating: "तैयार किया जा रहा है...",
      regenerateBtn: "रिपोर्ट फिर से बनाएं",
      generateBtn: "AI रिपोर्ट बनाएं",
      noReport: "अभी तक कोई रिपोर्ट नहीं बनाई गई है",
      emptyDesc: "अपनी इन्वेंटरी की विस्तृत AI रिपोर्ट बनाने के लिए ऊपर 'AI रिपोर्ट बनाएं' पर क्लिक करें।",
      execSummary: "कार्यकारी सारांश",
      movementAnalysis: "गतिविधि विश्लेषण",
      aiRecommendations: "AI सिफारिशें",
      reportTitle: "इन्वेंटरी विश्लेषण रिपोर्ट",
      generatedOn: "को तैयार किया गया"
    },
    invoice: {
      title: "इनवॉइस बनाएं",
      subtitle: "ग्राहकों के लिए बिलिंग इनवॉइस बनाएं",
      billTo: "बिल पता",
      clientName: "ग्राहक का नाम",
      clientEmail: "ग्राहक का ईमेल",
      invoiceDate: "इनवॉइस तिथि",
      addItem: "मद जोड़ें",
      product: "उत्पाद",
      qty: "मात्रा",
      price: "दर (₹)",
      total: "कुल",
      generateBtn: "इनवॉइस बनाएं",
      invoicesList: "सभी इनवॉइस",
      selectSupplier: "आपूर्तिकर्ता चुनें...",
      grandTotal: "कुल योग",
      typeLabel: "बिलिंग प्रकार",
      sales: "बिक्री",
      purchase: "खरीद",
      walkInCustomer: "सीधे ग्राहक",
      itemsTitle: "बिल आइटम",
      selectProduct: "उत्पाद चुनें...",
      preview: "इनवॉइस पूर्वावलोकन",
      allSuppliers: "सभी आपूर्तिकर्ता",
      noInvoices: "कोई इनवॉइस नहीं मिला।",
      subtotal: "उप-योग",
      supplier: "आपूर्तिकर्ता"
    },
    invoices: {
      title: "इनवॉइस लेजर",
      subtitle: "बनाए गए ग्राहक इनवॉइस देखें और प्रबंधित करें",
      invoiceNum: "इनवॉइस #",
      client: "ग्राहक का नाम",
      date: "दिनांक",
      amount: "राशि",
      actions: "कार्रवाई",
      viewPdf: "पीडीएफ देखें"
    },
    purchaseOrder: {
      title: "B2B खरीद आदेश",
      subtitle: "सत्यापित आपूर्तिकर्ताओं से स्टॉक ऑर्डर करें",
      createBtn: "खरीद आदेश बनाएं",
      supplier: "आपूर्तिकर्ता",
      products: "उत्पाद",
      orderDate: "आदेश दिनांक",
      status: "स्थिति",
      totalPrice: "कुल कीमत",
      statusSent: "भेजा गया",
      statusConfirmed: "पुष्टि की गई",
      statusReceived: "प्राप्त हुआ"
    },
    profile: {
      title: "मेरी प्रोफ़ाइल",
      subtitle: "अपना खाता प्रबंधित करें और प्रोजेक्ट क्रेडिट देखें",
      logout: "लॉगआउट",
      aboutTitle: "परियोजना के बारे में",
      developedBy: "द्वारा विकसित"
    },
    settings: {
      title: "सेटिंग्स",
      subtitle: "अपनी सिस्टम प्राथमिकताएं कॉन्फ़िगर करें",
      languageLabel: "सिस्टम भाषा",
      selectLanguage: "भाषा चुनें",
      saveSettings: "सेटिंग्स सहेजें",
      successMsg: "भाषा सफलतापूर्वक अपडेट की गई!"
    }
  },
  ta: {
    sidebar: {
      dashboard: "டாஷ்போர்டு",
      products: "தயாரிப்புகள்",
      stock: "பங்கு",
      ledger: "பங்கு லெட்ஜர்",
      suppliers: "வழங்குநர்கள்",
      voice: "குரல்",
      chat: "அரட்டை",
      aiReport: "AI அறிக்கை",
      reports: "அறிக்கைகள்",
      createInvoice: "இன்வாய்ஸ் உருவாக்கு",
      allInvoices: "அனைத்து இன்வாய்ஸ்கள்",
      purchaseOrder: "கொள்முதல் ஆணை",
      profile: "சுயவிவரம்",
      settings: "அமைப்புகள்"
    },
    dashboard: {
      title: "சரக்கு மேலோட்டம்",
      subtitle: "AI-இயக்கப்படும் பகுப்பாய்வு மற்றும் நிகழ்நேர கண்காணிப்பு",
      live: "சிஸ்டம் நேரலை",
      voiceAi: "குரல் AI",
      createInvoice: "இன்வாய்ஸ் உருவாக்கு",
      stockLedger: "பங்கு லெட்ஜர்",
      manageProducts: "தயாரிப்புகளை நிர்வகி",
      totalProducts: "மொத்த தயாரிப்புகள்",
      inventoryValue: "சரக்கு மதிப்பு",
      lowOutStock: "குறைந்த & தீர்ந்த பங்கு",
      topStocked: "அதிகம் சேமிக்கப்பட்ட தயாரிப்புகள்",
      healthScore: "ஆரோக்கிய மதிப்பெண்",
      healthCalculated: "தற்போதைய பங்கு நிலைகளின் அடிப்படையில் கணக்கிடப்பட்டது",
      criticalAlerts: "முக்கிய எச்சரிக்கைகள்",
      healthyMsg: "சரக்கு மிகவும் ஆரோக்கியமாக உள்ளது!",
      lowStockAlerts: "குறைந்த பங்கு எச்சரிக்கைகள்",
      needsRestock: "மீண்டும் நிரப்ப வேண்டும்",
      minStock: "குறைந்தபட்ச பங்கு அளவு",
      qty: "அளவு",
      restockBtn: "மறுவரிசைப்படுத்து",
      highDemand: "அதிக தேவை உள்ள தயாரிப்புகள்",
      topSellers: "அதிக விற்பனையானவை (30 நாட்கள்)",
      sold: "விற்கப்பட்டது",
      recentTransactions: "சமீபத்திய பரிவர்த்தனைகள்",
      viewLedger: "லெட்ஜரை காண்க",
      noActivity: "சமீபத்திய செயல்பாடுகள் ஏதுமில்லை.",
      loading: "டாஷ்போர்டு ஏற்றப்படுகிறது..."
    },
    products: {
      title: "தயாரிப்பு பட்டியல்",
      subtitle: "உங்கள் ஸ்மார்ட் சரக்கு உருப்படிகளை நிர்வகிக்கவும்",
      searchPlaceholder: "பெயர், வகை அல்லது SKU மூலம் தயாரிப்புகளைத் தேடுங்கள்...",
      addProductBtn: "தயாரிப்பு சேர்",
      id: "ஐடி",
      name: "தயாரிப்பு பெயர்",
      sku: "SKU",
      category: "வகை",
      quantity: "அளவு",
      price: "விலை",
      minStock: "குறைந்தபட்ச பங்கு",
      actions: "செயல்கள்",
      edit: "தொகு",
      delete: "அழி",
      noProducts: "தயாரிப்புகள் எதுவும் இல்லை.",
      addNewTitle: "புதிய தயாரிப்பு சேர்",
      editTitle: "தயாரிப்பைத் தொகுக்கவும்",
      saveBtn: "சேமி",
      cancelBtn: "ரத்துசெய்",
      categoryPlaceholder: "வகையைத் தேர்ந்தெடுக்கவும்",
      priceLabel: "விலை (₹)",
      qtyLabel: "துவக்க அளவு",
      minStockLabel: "குறைந்தபட்ச பங்கு அளவு",
      loading: "தயாரிப்புகள் ஏற்றப்படுகின்றன..."
    },
    stock: {
      title: "பங்கு மேலாண்மை",
      subtitle: "சரக்கு உருப்படிகளை விரைவாக நிரப்பவும் અથવા குறைக்கவும்",
      selectProduct: "தயாரிப்பைத் தேர்ந்தெடுக்கவும்",
      chooseProduct: "ஒரு தயாரிப்பைத் தேர்வு செய்யவும்...",
      action: "செயல்",
      add: "பங்கு சேர் (Restock)",
      remove: "பங்கைக் குறை (Deplete)",
      quantity: "அளவு",
      notes: "குறிப்புகள் / விளக்கம்",
      notesPlaceholder: "எ.கா. வழங்குநர் ஏற்றுமதி, சேதமடைந்த பொருட்கள்...",
      submitBtn: "பங்கைப் புதுப்பி",
      successMsg: "பங்கு வெற்றிகரமாகப் புதுப்பிக்கப்பட்டது",
      errorMsg: "பங்கைப் புதுப்பிக்கத் தவறிவிட்டது",
      loading: "பங்கு ஏற்றப்படுகிறது..."
    },
    ledger: {
      title: "பங்கு இயக்க வரலாறு",
      subtitle: "அனைத்து சரக்கு மாற்றங்களின் நிகழ்நேர தணிக்கை பதிவு",
      date: "தேதி மற்றும் நேரம்",
      product: "தயாரிப்பு",
      type: "வகை",
      change: "மாற்றம்",
      user: "பயனர்",
      notes: "குறிப்புகள்",
      added: "சேர்க்கப்பட்டது",
      removed: "நீக்கப்பட்டது (Deleted)",
      loading: "வரலாறு ஏற்றப்படுகிறது..."
    },
    suppliers: {
      title: "வழங்குநர் மேலாண்மை",
      subtitle: "சரக்கு வழங்குநர்கள் மற்றும் கூட்டாளர்களை நிர்வகி",
      addSupplier: "வழங்குநரைச் சேர்",
      name: "வழங்குநர் பெயர்",
      contact: "தொடர்பு நபர்",
      email: "மின்னஞ்சல் முகவரி",
      phone: "தொலைபேசி எண்",
      address: "முகவரி",
      actions: "செயல்கள்",
      noSuppliers: "வழங்குநர்கள் யாரும் பதிவு செய்யப்படவில்லை.",
      addNewTitle: "புதிய வழங்குநரைச் சேர்",
      editTitle: "வழங்குநரைத் தொகுக்கவும்",
      saveBtn: "சேமி",
      cancelBtn: "ரத்துசெய்",
      loading: "வழங்குநர்கள் ஏற்றப்படுகிறார்கள்..."
    },
    voice: {
      title: "குரல் AI கட்டுப்படுத்தி",
      subtitle: "இயற்கையான பேச்சு கட்டளைகளைப் பயன்படுத்தி உங்கள் சரக்குகளைக் கட்டுப்படுத்தவும்",
      listening: "கேட்கிறது...",
      clickMic: "பேச மைக்ரோஃபோனைக் கிளிக் செய்யவும்",
      exampleTitle: "இது போன்ற கட்டளைகளைச் சொல்ல முயற்சிக்கவும்:",
      ex1: "குறைந்த பங்கு உள்ள அனைத்து தயாரிப்புகளையும் காட்டு",
      ex2: "பங்கில் 50 மடிக்கணினிகளைச் சேர்",
      ex3: "மேசையின் விலையை 1500 ஆகப் புதுப்பி",
      status: "AI இயந்திரத்தின் நிலை",
      connected: "தயார்",
      lastCommand: "கடைசியாக செயலாக்கப்பட்ட கட்டளை:",
      processing: "செயலாக்கப்படுகிறது...",
      commandResult: "முடிவு:",
      speechUnsupported: "வலை பேச்சு API இந்த உலாவியில் ஆதரிக்கப்படவில்லை. தயவுசெய்து Chrome ஐப் பயன்படுத்தவும்."
    },
    chat: {
      title: "சரக்கு AI உடன் அரட்டையடிக்கவும்",
      subtitle: "இயற்கை மொழியைப் பயன்படுத்தி கேள்விகளைக் கேளுங்கள் அல்லது கட்டளைகளை இயக்கவும்",
      placeholder: "உங்கள் கட்டளையை உள்ளிடவும் (எ.கா. 20 நாற்காலிகள் சேர்)...",
      send: "அनुப்பு",
      welcome: "வணக்கம்! நான் உங்கள் ஸ்மார்ட் சரக்கு உதவியாளர். நீங்கள் பங்கை நிர்வகிக்கலாம், விலைகளைப் புதுப்பிக்கலாம் அல்லது கேள்விகளைக் கேட்கலாம். முயற்சி செய்க: 'குறைந்த பங்கு தயாரிப்புகளைக் காட்டு'",
      loading: "AI சிந்திக்கிறது..."
    },
    aiReport: {
      title: "AI அறிக்கை தயாரிப்பான்",
      subtitle: "AI ஆரோக்கிய பகுப்பாய்வுடன் கூடிய PDF அறிக்கையை உருவாக்குங்கள்",
      generateBtn: "PDF அறிக்கை உருவாக்கு",
      previewBtn: "அறிக்கை முன்னோட்டம்",
      analyzing: "AI தரவை பகுப்பாய்வு செய்கிறது...",
      generationSuccess: "PDF வெற்றிகரமாக உருவாக்கப்பட்டது!"
    },
    reports: {
      title: "சரக்கு அறிக்கைகள்",
      subtitle: "விஷுவல் அறிக்கைகள் மற்றும் சரக்கு ஆரோக்கிய தணிக்கை",
      downloadExcel: "எக்செல் பதிவிறக்கு",
      downloadPdf: "PDF பதிவிறக்கு",
      valueDistribution: "பங்கு மதிப்பு விநியோகம்",
      categoryAnalysis: "வகை பகுப்பாய்வு",
      generalHealth: "பொதுவான ஆரோக்கியம்",
      orderPlacement: "ஆர்டர் செய்தல்",
      restocking: "மீள்சேமிப்பு",
      refresh: "புதுப்பி",
      deadStock: "தேக்கச் சரக்கு",
      stockMovementTrend: "சரக்கு இயக்கப் போக்கு",
      inventoryHealth: "சரக்கு ஆரோக்கியம்",
      aiHealthScore: "AI சரக்கு ஆரோக்கிய மதிப்பெண்",
      goodStanding: "நல்ல நிலை",
      needsAttention: "கவனம் தேவை",
      critical: "முக்கியமான நிலை",
      inventoryValueByProduct: "தயாரிப்பு வாரியாக சரக்கு மதிப்பு",
      fastMovingProducts: "வேகமாக நகரும் தயாரிப்புகள்",
      deadStockItems: "தேக்கச் சரக்கு உருப்படிகள்",
      activeStockAlerts: "செயலில் உள்ள சரக்கு விழிப்பூட்டல்கள்",
      transactionHistory: "பரிவர்த்தனை வரலாறு",
      dateTime: "தேதி & நேரம்",
      type: "வகை",
      previous: "முந்தைய",
      newStock: "புதிய சரக்கு",
      totalB2BSpend: "மொத்த B2B செலவு",
      totalOrdersPlaced: "மொத்த கொள்முதல் ஆணைகள்",
      avgOrderValue: "சராசரி ஆர்டர் மதிப்பு",
      spendBySupplier: "வழங்குநர் வாரியாக செலவு",
      topProductsProcured: "அதிகம் பெறப்பட்ட தயாரிப்புகள்",
      purchaseOrdersLog: "B2B கொள்முதல் ஆணைப் பதிவு",
      products: "உருப்படிகள்",
      status: "நிலை",
      totalSpend: "மொத்த செலவு",
      received: "பெறப்பட்டது",
      sent: "அனுப்பப்பட்டது",
      confirmed: "உறுதிப்படுத்தப்பட்டது",
      qty: "சேர்க்கப்பட்ட அளவு",
      user: "பயனர்",
      print: "அச்சிடு",
      generating: "உருவாக்கப்படுகிறது...",
      regenerateBtn: "அறிக்கையை மீண்டும் உருவாக்கு",
      noReport: "இன்னும் அறிக்கை உருவாக்கப்படவில்லை",
      emptyDesc: "உங்கள் சரக்குகளின் விரிவான AI-இயக்க பகுப்பாய்வை உருவாக்க மேலே உள்ள 'AI அறிக்கையை உருவாக்கு' என்பதைக் கிளிக் செய்யவும்.",
      execSummary: "நிர்வாக சுருக்கம்",
      movementAnalysis: "இயக்க பகுப்பாய்வு",
      aiRecommendations: "AI பரிந்துரைகள்",
      reportTitle: "சரக்கு பகுப்பாய்வு அறிக்கை",
      generatedOn: "அறிக்கை உருவாக்கப்பட்ட தேதி",
      errorMsg: "அறிக்கையை உருவாக்க முடியவில்லை. பின்தளம் இயங்குவதையும் Groq API விசை உள்ளமைக்கப்பட்டிருப்பதையும் உறுதிப்படுத்தவும்."
    },
    invoice: {
      title: "இன்வாய்ஸ் உருவாக்கு",
      subtitle: "வாடிக்கையாளர்களுக்கான பில்லிங் இன்வாய்ஸை உருவாக்குங்கள்",
      billTo: "பில் செய்ய வேண்டியவர்",
      clientName: "வாடிக்கையாளர் பெயர்",
      clientEmail: "வாடிக்கையாளர் மின்னஞ்சல்",
      invoiceDate: "இன்வாய்ஸ் தேதி",
      addItem: "உருப்படியைச் சேர்",
      product: "தயாரிப்பு",
      qty: "அளவு",
      price: "விலை (₹)",
      total: "மொத்தம்",
      generateBtn: "இன்வாய்ஸ் உருவாக்கு",
      invoicesList: "அனைத்து இன்வாய்ஸ்கள்"
    },
    invoices: {
      title: "இன்வாய்ஸ் லெட்ஜர்",
      subtitle: "உருவாக்கப்பட்ட வாடிக்கையாளர் இன்வாய்ஸ்களை நிர்வகி",
      invoiceNum: "இன்வாய்ஸ் #",
      client: "வாடிக்கையாளர் பெயர்",
      date: "தேதி",
      amount: "தொகை",
      actions: "செயல்கள்",
      viewPdf: "PDF காண்க"
    },
    purchaseOrder: {
      title: "B2B கொள்முதல் ஆணைகள்",
      subtitle: "சரிபார்க்கப்பட்ட வழங்குநர்களிடமிருந்து பங்குகளை ஆர்டர் செய்யுங்கள்",
      createBtn: "கொள்முதல் ஆணையை உருவாக்கு",
      supplier: "வழங்குநர்",
      products: "தயாரிப்புகள்",
      orderDate: "ஆர்டர் தேதி",
      status: "நிலை",
      totalPrice: "மொத்த விலை",
      statusSent: "அனுப்பப்பட்டது",
      statusConfirmed: "உறுதிப்படுத்தப்பட்டது",
      statusReceived: "பெறப்பட்டது"
    },
    profile: {
      title: "எனது சுயவிவரம்",
      subtitle: "உங்கள் கணக்கை நிர்வகிக்கவும் மற்றும் திட்ட வரவுகளைப் பார்க்கவும்",
      logout: "வெளியேறு",
      aboutTitle: "திட்டம் பற்றி",
      developedBy: "உருவாக்கியவர்கள்"
    },
    settings: {
      title: "அமைப்புகள்",
      subtitle: "உங்கள் கணினி முன்னுரிமையை உள்ளமைக்கவும்",
      languageLabel: "கணினி மொழி",
      selectLanguage: "மொழியைத் தேர்ந்தெடு",
      saveSettings: "அமைப்புகளைச் சேமி",
      successMsg: "மொழி வெற்றிகரமாக சேமிக்கப்பட்டது!"
    }
  },
  pa: {
    sidebar: {
      dashboard: "ਡੈਸ਼ਬੋਰਡ",
      products: "ਉਤਪਾਦ",
      stock: "ਸਟਾਕ",
      ledger: "ਸਟਾਕ ਲੇਜ਼ਰ",
      suppliers: "ਸਪਲਾਇਰ",
      voice: "ਆਵਾਜ਼",
      chat: "ਚੈਟ",
      aiReport: "AI ਰਿਪੋਰਟ",
      reports: "ਰਿਪੋਰਟਾਂ",
      createInvoice: "ਇਨਵੌਇਸ ਬਣਾਓ",
      allInvoices: "ਸਾਰੇ ਇਨਵੌਇਸ",
      purchaseOrder: "ਖਰੀਦ ਆਰਡਰ",
      profile: "ਪ੍ਰੋਫਾਈਲ",
      settings: "ਸੈਟਿੰਗਾਂ"
    },
    dashboard: {
      title: "ਇਨਵੈਂਟਰੀ ਸੰਖੇਪ",
      subtitle: "AI-ਸੰਚਾਲਿਤ ਵਿਸ਼ਲੇਸ਼ਣ ਅਤੇ ਰੀਅਲ-ਟਾਈਮ ਟ੍ਰੈਕਿੰਗ",
      live: "ਸਿਸਟਮ ਲਾਈਵ",
      voiceAi: "ਵੌਇਸ AI",
      createInvoice: "ਇਨਵੌਇਸ ਬਣਾਓ",
      stockLedger: "ਸਟਾਕ ਲੇਜ਼ਰ",
      manageProducts: "ਉਤਪਾਦ ਪ੍ਰਬੰਧਨ",
      totalProducts: "ਕੁੱਲ ਉਤਪਾਦ",
      inventoryValue: "ਇਨਵੈਂਟਰੀ ਮੁੱਲ",
      lowOutStock: "ਘੱਟ ਅਤੇ ਖਤਮ ਸਟਾਕ",
      topStocked: "ਸਭ ਤੋਂ ਵੱਧ ਸਟਾਕ ਵਾਲੇ ਉਤਪਾਦ",
      healthScore: "ਸਿਹਤ ਸਕੋਰ",
      healthCalculated: "ਮੌਜੂਦਾ ਸਟਾਕ ਦੇ ਆਧਾਰ 'ਤੇ ਗਣਨਾ ਕੀਤੀ ਗਈ",
      criticalAlerts: "ਨਾਜ਼ੁਕ ਚੇਤਾਵਨੀਆਂ",
      healthyMsg: "ਇਨਵੈਂਟਰੀ ਬਿਲਕੁਲ ਤੰਦਰੁਸਤ ਹੈ!",
      lowStockAlerts: "ਘੱਟ ਸਟਾਕ ਚੇਤਾਵਨੀਆਂ",
      needsRestock: "ਦੁਬਾਰਾ ਭਰਨ ਦੀ ਲੋੜ ਹੈ",
      minStock: "ਘੱਟੋ-ਘੱਟ ਸਟਾਕ ਪੱਧਰ",
      qty: "ਮਾਤਰਾ",
      restockBtn: "ਮੁੜ ਆਰਡਰ ਕਰੋ",
      highDemand: "ਉੱਚ ਮੰਗ ਵਾਲੇ ਉਤਪਾਦ",
      topSellers: "ਸਭ ਤੋਂ ਵੱਧ ਵਿਕਣ ਵਾਲੇ (30 ਦਿਨ)",
      sold: "ਵੇਚੇ ਗਏ",
      recentTransactions: "ਹਾਲੀਆ ਲੈਣ-ਦੇਣ",
      viewLedger: "ਲੇਜ਼ਰ ਦੇਖੋ",
      noActivity: "ਕੋਈ ਹਾਲੀਆ ਗਤੀਵਿਧੀ ਨਹੀਂ ਮਿਲੀ।",
      loading: "ਡੈਸ਼ਬੋਰਡ ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ..."
    },
    products: {
      title: "ਉਤਪਾਦ ਕੈਟਾਲਾਗ",
      subtitle: "ਆਪਣੀਆਂ ਸਮਾਰਟ ਇਨਵੈਂਟਰੀ ਆਈਟਮਾਂ ਦੇਖੋ ਅਤੇ ਪ੍ਰਬੰਧਿਤ ਕਰੋ",
      searchPlaceholder: "ਨਾਮ, ਸ਼੍ਰੇਣੀ ਜਾਂ SKU ਦੁਆਰਾ ਉਤਪਾਦ ਖੋਜੋ...",
      addProductBtn: "ਉਤਪਾਦ ਜੋੜੋ",
      id: "ਆਈਡੀ",
      name: "ਉਤਪਾਦ ਦਾ ਨਾਮ",
      sku: "SKU",
      category: "ਸ਼੍ਰੇਣੀ",
      quantity: "ਮਾਤਰਾ",
      price: "ਕੀਮਤ",
      minStock: "ਘੱਟੋ-ਘੱਟ ਸਟਾਕ",
      actions: "ਕਾਰਵਾਈਆਂ",
      edit: "ਸੋਧੋ",
      delete: "ਹਟਾਓ",
      noProducts: "ਕੋਈ ਉਤਪਾਦ ਨਹੀਂ ਮਿਲਿਆ।",
      addNewTitle: "ਨਵਾਂ ਉਤਪਾਦ ਜੋੜੋ",
      editTitle: "ਉਤਪਾਦ ਸੋਧੋ",
      saveBtn: "ਸੰਭਾਲੋ",
      cancelBtn: "ਰੱਦ ਕਰੋ",
      categoryPlaceholder: "ਸ਼੍ਰੇਣੀ ਚੁਣੋ",
      priceLabel: "ਕੀਮਤ (₹)",
      qtyLabel: "ਸ਼ੁਰੂਆਤੀ ਮਾਤਰਾ",
      minStockLabel: "ਘੱਟੋ-ਘੱਟ ਸਟਾਕ ਪੱਧਰ",
      loading: "ਉਤਪਾਦ ਲੋਡ ਹੋ ਰਹੇ ਹਨ..."
    },
    stock: {
      title: "ਸਟਾਕ ਪ੍ਰਬੰਧਨ",
      subtitle: "ਇਨਵੈਂਟਰੀ ਆਈਟਮਾਂ ਨੂੰ ਜਲਦੀ ਭਰੋ ਜਾਂ ਘਟਾਓ",
      selectProduct: "ਉਤਪਾਦ ਚੁਣੋ",
      chooseProduct: "ਉਤਪਾਦ ਚੁਣੋ...",
      action: "ਕਾਰਵਾਈ",
      add: "ਸਟਾਕ ਜੋੜੋ (Restock)",
      remove: "ਸਟਾਕ ਘਟਾਓ (Deplete)",
      quantity: "ਮਾਤਰਾ",
      notes: "ਨੋਟਸ / ਵੇਰਵਾ",
      notesPlaceholder: "ਉਦਾਹਰਣ ਵਜੋਂ, ਸਪਲਾਇਰ ਸ਼ਿਪਮੈਂਟ, ਖਰਾਬ ਹੋਇਆ ਸਮਾਨ...",
      submitBtn: "ਸਟਾਕ ਅੱਪਡੇਟ ਕਰੋ",
      successMsg: "ਸਟਾਕ ਸਫਲਤਾਪੂਰਵਕ ਅੱਪਡੇਟ ਕੀਤਾ ਗਿਆ",
      errorMsg: "ਸਟਾਕ ਅੱਪਡੇਟ ਕਰਨ ਵਿੱਚ ਅਸਫਲ",
      loading: "ਸਟਾਕ ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ..."
    },
    ledger: {
      title: "ਸਟਾਕ ਮੂਵਮੈਂਟ ਇਤਿਹਾਸ",
      subtitle: "ਸਾਰੇ ਇਨਵੈਂਟਰੀ ਬਦਲਾਵਾਂ ਦਾ ਰੀਅਲ-ਟਾਈਮ ਆਡਿਟ ਲੌਗ",
      date: "ਮਿਤੀ ਅਤੇ ਸਮਾਂ",
      product: "ਉਤਪਾਦ",
      type: "ਕਿਸਮ",
      change: "ਬਦਲਾਅ",
      user: "ਉਪਭੋਗਤਾ",
      notes: "ਨੋਟਸ",
      added: "ਜੋੜਿਆ ਗਿਆ",
      removed: "ਮਿਟਾਇਆ ਗਿਆ (Deleted)",
      loading: "ਇਤਿਹਾਸ ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ..."
    },
    suppliers: {
      title: "ਸਪਲਾਇਰ ਪ੍ਰਬੰਧਨ",
      subtitle: "ਇਨਵੈਂਟਰੀ ਸਪਲਾਇਰਾਂ ਅਤੇ ਸਹਿਭਾਗੀਆਂ ਨੂੰ ਪ੍ਰਬੰਧਿਤ ਕਰੋ",
      addSupplier: "ਸਪਲਾਇਰ ਜੋੜੋ",
      name: "ਸਪਲਾਇਰ ਦਾ ਨਾਮ",
      contact: "ਸੰਪਰਕ ਵਿਅਕਤੀ",
      email: "ਈਮੇਲ ਪਤਾ",
      phone: "ਫ਼ੋਨ ਨੰਬਰ",
      address: "ਪਤਾ",
      actions: "ਕਾਰਵਾਈਆਂ",
      noSuppliers: "ਕੋਈ ਸਪਲਾਇਰ ਰਜਿਸਟਰਡ ਨਹੀਂ ਹੈ।",
      addNewTitle: "ਨਵਾਂ ਸਪਲਾਇਰ ਜੋੜੋ",
      editTitle: "ਸਪਲਾਇਰ ਸੋਧੋ",
      saveBtn: "ਸੰਭਾਲੋ",
      cancelBtn: "ਰੱਦ ਕਰੋ",
      loading: "ਸਪਲਾਇਰ ਲੋਡ ਹੋ ਰਹੇ ਹਨ..."
    },
    voice: {
      title: "ਵੌਇਸ AI ਕੰਟਰੋਲਰ",
      subtitle: "ਕੁਦਰਤੀ ਬੋਲੀ ਦੇ ਆਦੇਸ਼ਾਂ ਦੀ ਵਰਤੋਂ ਕਰਕੇ ਆਪਣੀ ਇਨਵੈਂਟਰੀ ਨੂੰ ਨਿਯੰਤਰਿਤ ਕਰੋ",
      listening: "ਸੁਣ ਰਿਹਾ ਹੈ...",
      clickMic: "ਬੋਲਣ ਲਈ ਮਾਈਕ 'ਤੇ ਕਲਿੱਕ ਕਰੋ",
      exampleTitle: "ਇਸ ਤਰ੍ਹਾਂ ਦੇ ਆਦੇਸ਼ ਬੋਲਣ ਦੀ ਕੋਸ਼ਿਸ਼ ਕਰੋ:",
      ex1: "ਘੱਟ ਸਟਾਕ ਵਾਲੇ ਸਾਰੇ ਉਤਪਾਦ ਦਿਖਾਓ",
      ex2: "ਸਟਾਕ ਵਿੱਚ 50 ਲੈਪਟਾਪ ਜੋੜੋ",
      ex3: "ਟੇਬਲ ਦੀ ਕੀਮਤ 1500 ਤੱਕ ਅੱਪਡੇਟ ਕਰੋ",
      status: "AI ਇੰਜਣ ਸਥਿਤੀ",
      connected: "ਤਿਆਰ",
      lastCommand: "ਆਖਰੀ ਪ੍ਰੋਸੈਸਡ ਆਦੇਸ਼:",
      processing: "ਪ੍ਰੋਸੈਸਿੰਗ ਹੋ ਰਹੀ ਹੈ...",
      commandResult: "ਨਤੀਜਾ:",
      speechUnsupported: "ਇਸ ਬ੍ਰਾਊਜ਼ਰ ਵਿੱਚ ਵੈੱਬ ਸਪੀਚ API ਸਮਰਥਿਤ ਨਹੀਂ ਹੈ। ਕਿਰਪਾ ਕਰਕੇ ਕ੍ਰੋਮ ਦੀ ਵਰਤੋਂ ਕਰੋ।"
    },
    chat: {
      title: "ਇਨਵੈਂਟਰੀ AI ਨਾਲ ਗੱਲਬਾਤ ਕਰੋ",
      subtitle: "ਕੁਦਰਤੀ ਭਾਸ਼ਾ ਦੀ ਵਰਤੋਂ ਕਰਕੇ ਪ੍ਰਸ਼ਨ ਪੁੱਛੋ ਜਾਂ ਆਦੇਸ਼ ਚਲਾਓ",
      placeholder: "ਆਪਣਾ ਆਦੇਸ਼ ਟਾਈਪ ਕਰੋ (ਜਿਵੇਂ ਕਿ 20 ਕੁਰਸੀਆਂ ਜੋੜੋ)...",
      send: "ਭੇਜੋ",
      welcome: "ਹੈਲੋ! ਮੈਂ ਤੁਹਾਡਾ ਸਮਾਰਟ ਇਨਵੈਂਟਰੀ ਸਹਾਇਕ ਹਾਂ। ਤੁਸੀਂ ਇੱਥੇ ਸਟਾਕ ਦਾ ਪ੍ਰਬੰਧਨ ਕਰ ਸਕਦੇ ਹੋ, ਕੀਮਤਾਂ ਅੱਪਡੇਟ ਕਰ ਸਕਦੇ ਹੋ ਜਾਂ ਸਵਾਲ ਪੁੱਛ ਸਕਦੇ ਹੋ। ਕੋਸ਼ਿਸ਼ ਕਰੋ: 'ਘੱਟ ਸਟਾਕ ਵਾਲੇ ਉਤਪਾਦ ਦਿਖਾਓ'",
      loading: "AI ਸੋਚ ਰਿਹਾ ਹੈ..."
    },
    aiReport: {
      title: "AI ਰਿਪੋਰਟ ਜਨਰੇਟਰ",
      subtitle: "AI-ਸੰਚਾਲਿਤ ਸਿਹਤ ਵਿਸ਼ਲੇਸ਼ਣ ਦੇ ਨਾਲ ਡਾਇਨਾਮਿਕ PDF ਰਿਪੋਰਟ ਤਿਆਰ ਕਰੋ",
      generateBtn: "PDF ਰਿਪੋਰਟ ਬਣਾਓ",
      previewBtn: "ਰਿਪੋਰਟ ਪੂਰਵਦਰਸ਼ਨ",
      analyzing: "AI ਨਾਲ ਡੇਟਾ ਦਾ ਵਿਸ਼ਲੇਸ਼ਣ ਕੀਤਾ ਜਾ ਰਿਹਾ ਹੈ...",
      generationSuccess: "PDF ਸਫਲਤਾਪੂਰਵਕ ਤਿਆਰ ਹੋ ਗਈ!"
    },
    reports: {
      title: "ਇਨਵੈਂਟਰੀ ਰਿਪੋਰਟਾਂ",
      subtitle: "ਵਿਜ਼ੂਅਲ ਰਿਪੋਰਟਾਂ ਅਤੇ ਇਨਵੈਂਟਰੀ ਸਿਹਤ ਆਡਿਟ",
      downloadExcel: "ਐਕਸਲ ਡਾਊਨਲੋਡ ਕਰੋ",
      downloadPdf: "PDF ਡਾਊਨਲੋਡ ਕਰੋ",
      valueDistribution: "ਸਟਾਕ ਮੁੱલ ਵੰਡ",
      categoryAnalysis: "ਸ਼੍ਰੇਣੀ ਵਿਸ਼ਲੇਸ਼ਣ",
      generalHealth: "ਆਮ ਸਿਹਤ",
      orderPlacement: "ਆਰਡਰ ਪਲੇਸਮੈਂਟ",
      restocking: "ਰੀਸਟੌਕਿੰਗ",
      refresh: "ਤਾਜ਼ਾ ਕਰੋ",
      deadStock: "ਡੇਡ ਸਟਾਕ",
      stockMovementTrend: "ਸਟਾਕ ਮੂਵਮੈਂਟ ਟ੍ਰੈਂਡ",
      inventoryHealth: "ਇਨਵੈਂਟਰੀ ਸਿਹਤ",
      aiHealthScore: "AI ਇਨਵੈਂਟਰੀ ਸਿਹਤ ਸਕੋਰ",
      goodStanding: "ਚੰਗੀ ਸਥਿਤੀ",
      needsAttention: "ਧਿਆਨ ਦੇਣ ਦੀ ਲੋੜ ਹੈ",
      critical: "ਨਾਜ਼ੁਕ",
      inventoryValueByProduct: "ਉਤਪਾਦ ਅਨੁਸਾਰ ਇਨਵੈਂਟਰੀ ਮੁੱલ",
      fastMovingProducts: "ਤੇਜ਼ੀ ਨਾਲ ਵਿਕਣ ਵਾਲੇ ਉਤਪாਦ",
      deadStockItems: "ਡੇਡ ਸਟਾਕ ਆਈਟਮਾਂ",
      activeStockAlerts: "ਸਰਗਰਮ ਸਟਾਕ ਚੇਤਾਵਨੀਆਂ",
      transactionHistory: "ਲੈਣ-ਦੇਣ ਦਾ ਇਤਿਹਾਸ",
      dateTime: "ਮਿਤੀ ਅਤੇ ਸਮਾਂ",
      type: "ਕਿਸਮ",
      previous: "ਪਿਛਲਾ ਸਟਾਕ",
      newStock: "ਨਵਾਂ ਸਟਾਕ",
      totalB2BSpend: "ਕੁੱਲ B2B ਖਰਚ",
      totalOrdersPlaced: "ਕੁੱਲ ਖਰੀਦ ਆਰਡਰ",
      avgOrderValue: "ਔਸਤ ਆਰਡਰ ਮੁੱલ",
      spendBySupplier: "ਸਪਲਾਇਰ ਅਨੁਸਾਰ ਖਰਚ",
      topProductsProcured: "ਚੋਟੀ ਦੇ ਖਰੀਦੇ ਉਤਪਾਦ",
      purchaseOrdersLog: "B2B ਖਰੀਦ ਆਰਡਰ ਲੌਗ",
      products: "ਆਈਟਮਾਂ",
      status: "ਸਥਿਤੀ",
      totalSpend: "ਕੁੱล ਖਰਚ",
      received: "ਪ੍ਰਾਪਤ ਹੋਇਆ",
      sent: "ਭੇਜਿਆ",
      confirmed: "ਪੁਸ਼ਟੀ ਹੋਈ",
      qty: "ਜੋੜੀ ਗਈ ਮਾਤਰਾ",
      user: "ਉਪਭੋਗਤਾ",
      print: "ਪ੍ਰਿੰਟ ਕਰੋ",
      generating: "ਤਿਆਰ ਕੀਤਾ ਜਾ ਰਿਹਾ ਹੈ...",
      regenerateBtn: "ਰਿਪੋਰਟ ਦੁਬਾਰਾ ਬਣਾਓ",
      noReport: "ਅਜੇ ਤੱਕ ਕੋਈ ਰਿਪੋਰਟ ਨਹੀਂ ਬਣੀ",
      emptyDesc: "ਆਪਣੀ ਇਨਵੈਂਟਰੀ ਦਾ ਵਿਆਪਕ, AI-ਸੰਚਾਲਿਤ ਵਿਸ਼ਲੇਸ਼ણ ਬਣਾਉਣ ਲਈ ਉੱਪਰ ਦਿੱਤੇ \"AI ਰਿਪੋਰਟ ਤਿਆਰ ਕਰੋ\" 'ਤੇ ਕਲਿੱਕ ਕਰੋ।",
      execSummary: "ਕਾਰਜਕਾਰੀ ਸਾਰਾਂਸ਼",
      movementAnalysis: "ਮੂਵਮੈਂਟ ਵਿਸ਼ਲੇਸ਼ਣ",
      aiRecommendations: "AI ਸਿਫ਼ਾਰਿਸ਼ਾਂ",
      reportTitle: "ਇਨਵੈਂਟਰੀ ਵਿਸ਼ਲੇਸ਼ਣ ਰਿਪੋਰਟ",
      generatedOn: "ਰਿਪੋਰਟ ਬਣਨ ਦੀ ਮਿਤੀ",
      errorMsg: "ਰਿਪੋਰਟ ਤਿਆਰ ਕਰਨ ਵਿੱਚ ਅਸਫਲ। ਕਿਰਪਾ ਕਰਕੇ ਯਕੀਨੀ ਬਣਾਓ ਕਿ ਬੈਕਐਂਡ ਚੱਲ ਰਿਹਾ ਹੈ ਅਤੇ Groq API ਕੁੰਜੀ ਕੌਂਫਿਗਰ ਕੀਤੀ ਗਈ ਹੈ।"
    },
    invoice: {
      title: "ਇਨਵੌਇਸ ਬਣਾਓ",
      subtitle: "ਗਾਹਕਾਂ ਲਈ ਬਿਲਿੰਗ ਇਨਵੌਇਸ ਤਿਆਰ ਕਰੋ",
      billTo: "ਬਿੱਲ ਭੇਜੋ",
      clientName: "ਗਾਹਕ ਦਾ ਨਾਮ",
      clientEmail: "ਗਾਹਕ ਦੀ ਈਮੇਲ",
      invoiceDate: "ਇਨਵੌਇਸ ਮਿਤੀ",
      addItem: "ਆਈਟਮ ਜੋੜੋ",
      product: "ਉਤਪਾਦ",
      qty: "ਮਾਤਰਾ",
      price: "ਕੀਮਤ (₹)",
      total: "ਕੁੱਲ",
      generateBtn: "ਇਨਵੌਇਸ ਬਣਾਓ",
      invoicesList: "ਸਾਰੇ ਇਨਵੌਇਸ"
    },
    invoices: {
      title: "ਇਨਵੌਇਸ ਲੇਜ਼ਰ",
      subtitle: "ਬਣਾਏ ਗਏ ਗਾਹਕ ਇਨਵੌਇਸ ਦੇਖੋ ਅਤੇ ਪ੍ਰਬੰਧਿਤ ਕਰੋ",
      invoiceNum: "ਇਨਵੌਇਸ #",
      client: "ਗਾਹਕ ਦਾ ਨਾਮ",
      date: "ਮਿਤੀ",
      amount: "ਰਕਮ",
      actions: "ਕਾਰਵਾਈਆਂ",
      viewPdf: "PDF ਦੇਖੋ"
    },
    purchaseOrder: {
      title: "B2B ਖਰੀਦ ਆਰਡਰ",
      subtitle: "ਸਮਰਥਿਤ ਸਪਲਾਇਰਾਂ ਤੋਂ ਸਟਾਕ ਆਰਡਰ ਕਰੋ",
      createBtn: "ਖਰੀਦ ਆਰਡਰ ਬਣਾਓ",
      supplier: "ਸਪਲਾਇਰ",
      products: "ਉਤਪਾਦ",
      orderDate: "ਆਰਡਰ ਮਿਤੀ",
      status: "ਸਥਿਤੀ",
      totalPrice: "ਕੁੱਲ ਕੀਮਤ",
      statusSent: "ਭੇਜਿਆ",
      statusConfirmed: "ਪੁਸ਼ਟੀ ਹੋਈ",
      statusReceived: "ਪ੍ਰਾਪਤ ਹੋਇਆ"
    },
    profile: {
      title: "ਮੇਰੀ ਪ੍ਰੋਫਾਈਲ",
      subtitle: "ਆਪਣੇ ਖਾਤੇ ਦਾ ਪ੍ਰਬੰਧਨ ਕਰੋ ਅਤੇ ਪ੍ਰੋਜੈਕਟ ਕ੍ਰੈਡਿਟ ਦੇਖੋ",
      logout: "ਲੌਗਆਉਟ",
      aboutTitle: "ਪ੍ਰੋਜੈਕਟ ਬਾਰੇ",
      developedBy: "ਦੁਆਰਾ ਵਿਕਸਿਤ ਕੀਤਾ"
    },
    settings: {
      title: "ਸੈਟਿੰਗਾਂ",
      subtitle: "ਆਪਣੀ ਸਿਸਟਮ ਤਰਜੀਹਾਂ ਨੂੰ ਕੌਂਫਿਗਰ ਕਰੋ",
      languageLabel: "ਸਿਸਟਮ ਭਾਸ਼ਾ",
      selectLanguage: "ਭਾਸ਼ਾ ਚੁਣੋ",
      saveSettings: "ਸੈਟਿੰਗਾਂ ਸੰਭਾਲੋ",
      successMsg: "ਸੈਟਿੰਗਾਂ ਸਫਲਤਾਪੂਰਵਕ ਸੁਰੱਖਿਅਤ ਕੀਤੀਆਂ ਗਈਆਂ!"
    }
  },
  gu: {
    sidebar: {
      dashboard: "ડેશબોર્ડ",
      products: "ઉત્પાદનો",
      stock: "સ્ટોક",
      ledger: "સ્ટોક લેજર",
      suppliers: "સપ્લાયર્સ",
      voice: "અવાજ",
      chat: "ચેટ",
      aiReport: "AI રિપોર્ટ",
      reports: "અહેવાલો",
      createInvoice: "ઇનવોઇસ બનાવો",
      allInvoices: "બધા ઇનવોઇસ",
      purchaseOrder: "ખરીદી ઓર્ડર",
      profile: "પ્રોફાઇલ",
      settings: "સેટિંગ્સ"
    },
    dashboard: {
      title: "ઇન્વેન્ટરી વિહંગાવલોકન",
      subtitle: "AI-સંચાલિત વિશ્લેષણ અને રીઅલટાઇમ ટ્રેકિંગ",
      live: "સિસ્ટમ લાઇવ છે",
      voiceAi: "વોઇસ AI",
      createInvoice: "ઇનવોઇસ બનાવો",
      stockLedger: "સ્ટોક લેજર",
      manageProducts: "ઉત્પાદનોનું સંચાલન",
      totalProducts: "કુલ ઉત્પાદનો",
      inventoryValue: "ઇન્વેન્ટરી મૂલ્ય",
      lowOutStock: "ઓછો અને ખાલી સ્ટોક",
      topStocked: "ટોચના સ્ટોકવાળા ઉત્પાદનો",
      healthScore: "હેલ્થ સ્કોર",
      healthCalculated: "વર્તમાન સ્ટોક સ્તરના આધારે ગણતરી",
      criticalAlerts: "મહત્વપૂર્ણ ચેતવણીઓ",
      healthyMsg: "ઇન્વેન્ટરી સંપૂર્ણપણે તંદુરસ્ત છે!",
      lowStockAlerts: "ઓછા સ્ટોકની ચેતવણીઓ",
      needsRestock: "ફરીથી ભરવાની જરૂર છે",
      minStock: "ન્યૂનતમ સ્ટોક સ્તર",
      qty: "જથ્થો",
      restockBtn: "ફરીથી ઓર્ડર કરો",
      highDemand: "ઉચ્ચ માંગવાળા ઉત્પાદનો",
      topSellers: "ટોચના વિક્રેતાઓ (30 દિવસ)",
      sold: "વેચાયા",
      recentTransactions: "તાજેતરના વ્યવહારો",
      viewLedger: "લેજર જુઓ",
      noActivity: "કોઈ તાજેતરની પ્રવૃત્તિ મળી નથી.",
      loading: "ડેશબોર્ડ લોડ થઈ રહ્યું છે..."
    },
    products: {
      title: "ઉત્પાદન સૂચિ",
      subtitle: "તમારા સ્માર્ટ ઇન્વેન્ટરી વસ્તુઓ જુઓ અને સંચાલિત કરો",
      searchPlaceholder: "નામ, શ્રેણી અથવા SKU દ્વારા ઉત્પાદનો શોધો...",
      addProductBtn: "ઉત્પાદન ઉમેરો",
      id: "આઈડી",
      name: "ઉત્પાદન નામ",
      sku: "SKU",
      category: "શ્રેણી",
      quantity: "જથ્થો",
      price: "કિંમત",
      minStock: "ન્યૂનતમ સ્ટોક",
      actions: "ક્રિયાઓ",
      edit: "ફેરફાર કરો",
      delete: "કાઢી નાખો",
      noProducts: "કોઈ ઉત્પાદનો મળ્યા નથી.",
      addNewTitle: "નવું ઉત્પાદન ઉમેરો",
      editTitle: "ઉત્પાદનમાં ફેરફાર કરો",
      saveBtn: "સાચવો",
      cancelBtn: "રદ કરો",
      categoryPlaceholder: "શ્રેણી પસંદ કરો",
      priceLabel: "કિંમત (₹)",
      qtyLabel: "પ્રારંભિક જથ્થો",
      minStockLabel: "ન્યૂનતમ સ્ટોક સ્તર",
      loading: "ઉત્પાદનો લોડ થઈ રહ્યા છે..."
    },
    stock: {
      title: "સ્ટોક મેનેજમેન્ટ",
      subtitle: "ઇન્વેન્ટરી વસ્તુઓ ઝડપથી ફરીથી ભરો અથવા ઓછી કરો",
      selectProduct: "ઉત્પાદન પસંદ કરો",
      chooseProduct: "ઉત્પાદન પસંદ કરો...",
      action: "ક્રિયા",
      add: "સ્ટોક ઉમેરો (Restock)",
      remove: "સ્ટોક ઓછો કરો (Deplete)",
      quantity: "જથ્થો",
      notes: "નોંધો / વર્ણન",
      notesPlaceholder: "દા.ત. સપ્લાયર શિપમેન્ટ, નુકસાન પામેલ માલ...",
      submitBtn: "સ્ટોક અપડેટ કરો",
      successMsg: "સ્ટોક સફળતાપૂર્વક અપડેટ થયો",
      errorMsg: "સ્ટોક અપડેટ કરવામાં નિષ્ફળ",
      loading: "સ્ટોક લોડ થઈ રહ્યો છે..."
    },
    ledger: {
      title: "સ્ટોક હિલચાલનો ઇતિહાસ",
      subtitle: "બધા ઇન્વેન્ટરી ફેરફારોની રીઅલ-ટાઇમ ઓડિટ લોગ",
      date: "તારીખ અને સમય",
      product: "ઉત્પાદન",
      type: "પ્રકાર",
      change: "બદલાવ",
      user: "વપરાશકર્તા",
      notes: "નોંધો",
      added: "ઉમેર્યું",
      removed: "કાઢી નાખ્યું (Deleted)",
      loading: "ઇતિહાસ લોડ થઈ રહ્યો છે..."
    },
    suppliers: {
      title: "સપ્લાયર મેનેજમેન્ટ",
      subtitle: "ઇન્વેન્ટરી સપ્લાયર્સ અને ભાગીદારોનું સંચાલન કરો",
      addSupplier: "સપ્લાયર ઉમેરો",
      name: "સપ્લાયર નામ",
      contact: "સંપર્ક વ્યક્તિ",
      email: "ઇમેઇલ સરનામું",
      phone: "ફોન નંબર",
      address: "સરનામું",
      actions: "ક્રિયાઓ",
      noSuppliers: "કોઈ સપ્લાયર્સ નોંધાયેલા નથી.",
      addNewTitle: "નવો સપ્લાયર ઉમેરો",
      editTitle: "સપ્લાયરમાં ફેરફાર કરો",
      saveBtn: "સાચવો",
      cancelBtn: "રદ કરો",
      loading: "સપ્લાયર્સ લોડ થઈ રહ્યા છે..."
    },
    voice: {
      title: "વોઇસ AI કંટ્રોલર",
      subtitle: "કુદરતી ભાષણ આદેશોનો ઉપયોગ કરીને તમારી ઇન્વેન્ટરીને નિયંત્રિત કરો",
      listening: "સાંભળી રહ્યું છે...",
      clickMic: "તમારો આદેશ બોલવા માટે માઇક પર ક્લિક કરો",
      exampleTitle: "આવા આદેશો બોલવાનો પ્રયાસ કરો:",
      ex1: "ઓછા સ્ટોકવાળા બધા ઉત્પાદનો બતાવો",
      ex2: "સ્ટોકમાં 50 લેપટોપ ઉમેરો",
      ex3: "ટેબલની કિંમત 1500 સુધી અપડેટ કરો",
      status: "AI એન્જિન સ્થિતિ",
      connected: "ત્યાર",
      lastCommand: "છેલ્લે પ્રક્રિયા કરેલ આદેશ:",
      processing: "પ્રક્રિયા થઈ રહી છે...",
      commandResult: "પરિણામ:",
      speechUnsupported: "આ બ્રાઉઝરમાં વેબ સ્પીચ API સપોર્ટેડ નથી. કૃપા કરીને ક્રોમનો ઉપયોગ કરો."
    },
    chat: {
      title: "ઇન્વેન્ટરી AI સાથે ચેટ કરો",
      subtitle: "કુદરતી ભાષાનો ઉપયોગ કરીને પ્રશ્નો પૂછો અથવા આદેશો ચલાવો",
      placeholder: "તમારો આદેશ લખો (દા.ત. 20 ખુરશીઓ ઉમેરો)...",
      send: "મોકલો",
      welcome: "નમસ્તે! હું તમારો સ્માર્ટ ઇન્વેન્ટરી સહાયક છું. તમે અહીં સ્ટોક મેનેજ કરી શકો છો, કિંમતો અપડેટ કરી શકો છો અથવા પ્રશ્નો પૂછી શકો છો. પ્રયત્ન કરો: 'ઓછા સ્ટોકવાળા ઉત્પાદનો બતાવો'",
      loading: "AI વિચારી રહ્યું છે..."
    },
    aiReport: {
      title: "AI રિપોર્ટ જનરેટર",
      subtitle: "AI-સંચાલિત આરોગ્ય વિશ્લેષણ સાથે ડાયનેમિક PDF રિપોર્ટ બનાવો",
      generateBtn: "PDF રિપોર્ટ બનાવો",
      previewBtn: "રિપોર્ટ પૂર્વાવલોકન",
      analyzing: "AI સાથે ડેટાનું વિશ્લેષણ કરવામાં આવી રહ્યું છે...",
      generationSuccess: "PDF સફળતાપૂર્વક જનરેટ થઈ!"
    },
    reports: {
      title: "ઇન્વેન્ટરી અહેવાલો",
      subtitle: "દ્રશ્ય અહેવાલો અને ઇન્વેન્ટરી આરોગ્ય ઓડિટ",
      downloadExcel: "એક્સેલ ડાઉનલોડ કરો",
      downloadPdf: "PDF ડાઉનલોડ કરો",
      valueDistribution: "સ્ટોક મૂલ્ય વિતરણ",
      categoryAnalysis: "શ્રેણી વિશ્લેષણ",
      generalHealth: "સામાન્ય આરોગ્ય",
      orderPlacement: "ઓર્ડર પ્લેસમેન્ટ",
      restocking: "રીસ્ટોકિંગ",
      refresh: "તાજું કરો",
      deadStock: "ડેડ સ્ટોક",
      stockMovementTrend: "સ્ટોક મૂવમેન્ટ ટ્રેન્ડ",
      inventoryHealth: "ઇન્વેન્ટરી હેલ્થ",
      aiHealthScore: "AI ઇન્વેન્ટરી હેલ્થ સ્કોર",
      goodStanding: "સારી સ્થિતિ",
      needsAttention: "ધ્યાન આપવાની જરૂર છે",
      critical: "ગંભીર",
      inventoryValueByProduct: "પ્રોડક્ટ દ્વારા ઇન્વેન્ટરી મૂલ્ય",
      fastMovingProducts: "ઝડપથી વેચાતી પ્રોડક્ટ્સ",
      deadStockItems: "ડેડ સ્ટોક આઇટમ્સ",
      activeStockAlerts: "સક્રિય સ્ટોક ચેતવણીઓ",
      transactionHistory: "વ્યવહાર ઇતિહાસ",
      dateTime: "તારીખ અને સમય",
      type: "પ્રકાર",
      previous: "અગાઉનો સ્ટોક",
      newStock: "નવો સ્ટોક",
      totalB2BSpend: "કુલ B2B ખર્ચ",
      totalOrdersPlaced: "કુલ ખરીદી ઓર્ડર",
      avgOrderValue: "સરેરાશ ઓર્ડર મૂલ્ય",
      spendBySupplier: "સપ્લાયર દ્વારા ખર્ચ",
      topProductsProcured: "ટોચની ખરીદેલ પ્રોડક્ટ્સ",
      purchaseOrdersLog: "B2B ખરીદી ઓર્ડર લોગ",
      products: "આઇટમ્સ",
      status: "સ્થિતિ",
      totalSpend: "કુલ ખર્ચ",
      received: "મળેલ",
      sent: "મોકલેલ",
      confirmed: "પુષ્ટિ થયેલ",
      qty: "ઉમેરેલ જથ્થો",
      user: "વપરાશકર્તા",
      print: "પ્રિન્ટ કરો",
      generating: "તૈયાર થઈ રહ્યું છે...",
      regenerateBtn: "રિપોર્ટ ફરીથી બનાવો",
      noReport: "હજુ સુધી કોઈ રિપોર્ટ જનરેટ થયો નથી",
      emptyDesc: "તમારી ઇન્વેન્ટરીનું વ્યાપક, AI-આધારિત વિશ્લેષણ બનાવવા માટે ઉપરના \"AI રિપોર્ટ બનાવો\" પર ક્લિક કરો.",
      execSummary: "કાર્યકારી સારાંશ",
      movementAnalysis: "મૂવમેન્ટ વિશ્લેષણ",
      aiRecommendations: "AI ભલામણો",
      reportTitle: "ઇન્વેન્ટરી વિશ્લેષણ અહેવાલ",
      generatedOn: "રિપોર્ટ જનરેટ થયાની તારીખ",
      errorMsg: "અહેવાલ બનાવવામાં નિષ્ફળ. કૃપા કરીને ખાતરી કરો કે બેકએન્ડ ચાલુ છે અને Groq API કી ગોઠવેલ છે."
    },
    invoice: {
      title: "ઇનવોઇસ બનાવો",
      subtitle: "ગ્રાહકો માટે બિલિંગ ઇનવોઇસ બનાવો",
      billTo: "બિલ મોકલો",
      clientName: "ગ્રાહક નામ",
      clientEmail: "ગ્રાહક ઇમેઇલ",
      invoiceDate: "ઇનવોઇસ તારીખ",
      addItem: "વસ્તુ ઉમેરો",
      product: "ઉત્પાદન",
      qty: "જથ્થો",
      price: "કિંમત (₹)",
      total: "કુલ",
      generateBtn: "ઇનવોઇસ બનાવો",
      invoicesList: "બધા ઇનવોઇસ"
    },
    invoices: {
      title: "ઇનવોઇસ લેજર",
      subtitle: "બનાવેલા ગ્રાહક ઇનવોઇસ જુઓ અને સંચાલિત કરો",
      invoiceNum: "ઇનવોઇસ #",
      client: "ગ્રાહક નામ",
      date: "તારીખ",
      amount: "રકમ",
      actions: "ક્રિયાઓ",
      viewPdf: "PDF જુઓ"
    },
    purchaseOrder: {
      title: "B2B ખરીદી ઓર્ડર્સ",
      subtitle: "ચકાસાયેલ સપ્લાયર્સ પાસેથી સ્ટોક ઓર્ડર કરો",
      createBtn: "ખરીદી ઓર્ડર બનાવો",
      supplier: "સપ્લાયર",
      products: "ઉત્પાદનો",
      orderDate: "ઓર્ડર તારીખ",
      status: "સ્થિતિ",
      totalPrice: "કુલ કિંમત",
      statusSent: "મોકલેલ",
      statusConfirmed: "પુષ્ટિ થયેલ",
      statusReceived: "મળેલ"
    },
    profile: {
      title: "મારી પ્રોફાઇલ",
      subtitle: "તમારું ખાતું સંચાલિત કરો અને પ્રોજેક્ટ ક્રેડિટ્સ જુઓ",
      logout: "લોગઆઉટ",
      aboutTitle: "પ્રોજેક્ટ વિશે",
      developedBy: "દ્વારા વિકસિત"
    },
    settings: {
      title: "સેટિંગ્સ",
      subtitle: "તમારી સિસ્ટમ પસંદગીઓ ગોઠવો",
      languageLabel: "સિસ્ટમ ભાષા",
      selectLanguage: "ભાષા પસંદ કરો",
      saveSettings: "સેટિંગ્સ સાચવો",
      successMsg: "સેટિંગ્સ સફળતાપૂર્વક સાચવવામાં આવી!"
    }
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('system_language') || 'en';
  });

  const changeLanguage = (lang) => {
    setLanguage(lang);
    localStorage.setItem('system_language', lang);
  };

  const t = (keyPath) => {
    const keys = keyPath.split('.');
    let translation = translations[language] || translations.en;
    
    for (const key of keys) {
      if (translation && translation[key] !== undefined) {
        translation = translation[key];
      } else {
        // Fallback to English if key is missing in active language
        let fallback = translations.en;
        for (const fKey of keys) {
          if (fallback && fallback[fKey] !== undefined) {
            fallback = fallback[fKey];
          } else {
            return keyPath; // Return key path if not found anywhere
          }
        }
        return fallback;
      }
    }
    return translation;
  };

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t, languages: Object.keys(translations) }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
